### ISSUE TITLE
Simple derivative is very slow

### ISSUE THREAD

**Issue by saschatimme** [FluxML/Zygote.jl#10]
I tried the most simple example
```julia
julia> f(x) = 3x^2 + 2x + 1
f (generic function with 1 method)

julia> f′(x) = derivative(f, x)
f′ (generic function with 1 method)
```
But the performance of the derivative is way too slow (this should be rather something like 2ns):
```julia
julia> @btime f′($5.0)
  8.095 μs (77 allocations: 1.92 KiB)
32.0
```

**Comment by MikeInnes** [comment]
From the compiler's perspective this is not so simple :) `x^2` actually lowers to something like `Base.literal_pow(x, Val(2))` – I just pushed a fix to make sure we're handling that properly. The `a+b+c` also involves handling varargs and `apply`, which for now is slow; but you can avoid that with `(a+b)+c`.

Another sticky point about benchmarking Zygote – for reasons I don't fully understand, but which are probably to do with world ages and function visibility, the optimisations don't kick in properly unless you run things once and then `refresh()`. For example, this timing script gives results in under 2ns, whereas a simpler version gives more like 1mus.

```julia
using Zygote, BenchmarkTools
using Zygote: gradient

f(x) = (3x^2+2x)+1
gradient(f, 5)

Zygote.refresh()

gradient(f, 5)
@benchmark gradient(f, 5)
```

**Comment by chriselrod** [comment]
I am getting a minor performance improvement, but still around 1 microsecond.
```julia

julia> using Zygote, BenchmarkTools
[ Info: Recompiling stale cache file /home/chris/.julia/compiled/v1.0/BenchmarkTools/ZXPQo.ji for BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]

julia> using Zygote: gradient

julia> f(x) = (3x^2+2x)+1
f (generic function with 1 method)

julia> gradient(f, 5)
(32.0,)

julia> @benchmark gradient(f, 5)
BenchmarkTools.Trial: 
  memory estimate:  1.73 KiB
  allocs estimate:  51
  --------------
  minimum time:     1.563 μs (0.00% GC)
  median time:      1.660 μs (0.00% GC)
  mean time:        2.334 μs (26.69% GC)
  maximum time:     4.647 ms (99.91% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> Zygote.refresh()

julia> gradient(f, 5)
(32.0,)

julia> @benchmark gradient(f, 5)
BenchmarkTools.Trial: 
  memory estimate:  1.23 KiB
  allocs estimate:  33
  --------------
  minimum time:     1.159 μs (0.00% GC)
  median time:      1.223 μs (0.00% GC)
  mean time:        1.987 μs (35.79% GC)
  maximum time:     4.913 ms (99.92% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> Zygote.refresh()

julia> @benchmark gradient(f, 5)
BenchmarkTools.Trial: 
  memory estimate:  1.23 KiB
  allocs estimate:  33
  --------------
  minimum time:     1.117 μs (0.00% GC)
  median time:      1.197 μs (0.00% GC)
  mean time:        1.961 μs (36.38% GC)
  maximum time:     4.905 ms (99.93% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> versioninfo()
Julia Version 1.0.0
Commit ece21e1ae5 (2018-08-29 14:15 UTC)
```

**Comment by MikeInnes** [comment]
I got this down to a few hundred ns; not perfect, but at least that gets rid of all the really dumb issues.

For now, you'll need the Julia branch mentioned on the readme to get really good performance. I'm hoping to fix that for many more cases in future.

**Comment by chriselrod** [comment]
Note that
```julia
julia> versioninfo()
Julia Version 1.0.0
Commit ece21e1ae5 (2018-08-29 14:15 UTC)
```
is the latest commit on this branch: https://github.com/JuliaLang/julia/tree/mji/zygote

I'll rebuild next time I notice you've pushed updates and test again.
