### ISSUE TITLE
`unique()` error in pullback

### ISSUE THREAD

**Issue by DavidKoplow** [FluxML/Zygote.jl#1053]
I need to calculate the pullback of a function which uses `unique()`. The variable being differentiated isn't fed into `unique()` as an argument. On the forward pass everything seems fine, but on the backwards pass Zygote sets the output of `unique()` to `IRTools.Inner.Undefined()`. Here is the MWE:

```
function f1(A)
    @show unique([1])
    A
end
f1(5) #unique returns correct result
Zygote._pullback(f1,5) #unique returns IRTools.Inner.Undefined()
```
In the above example Zygote is able to correctly calculate both pullbacks, but in the program I am working on, `IRTools.Inner.Undefined()` leads to an error, which causes the whole thing to crash. For the rest of the code to work, I need to keep `unique()` in.

Has anyone encountered this issue? What is the fix?

**Comment by mcabbott** [comment]
The quick fix is:
```julia
julia> gradient(x -> sum(abs2, Zygote.forwarddiff(unique, x)), [1,1,2,3,2])
([2, 0, 4, 6, 0],)

julia> gradient(x -> sum(abs2, unique(x)), [1,1,2,3,2])
ERROR: MethodError: no method matching iterate(::IRTools.Inner.Undefined)
```
Beyond that, someone should write a rule for `unique`, ideally into ChainRules.jl so that it can be used elsewhere too. While `sort` has `sortperm` there is (I think) no obvious built-in function which will tell the indices of the surviving elements in the original array.

**Comment by DavidKoplow** [comment]
Unfortunately, for this use case I need to use reverse mode AD. Are you sure this is a result of there not being a `unique` definition in ChainRules.jl? In the MWE the `unique` call doesn't effect the derivative of `A` at all.

**Comment by mcabbott** [comment]
I guess there could be a short-cut method for unique on length-1 vectors, but nobody wrote it? In general it's making some Set and checking whether (hashes of?) elements appear in that, which it's understandable that Zygote finds hard to digest. (Enzyme too, I just tried.)

What I wrote is some mixed-mode thing, it is using ForwardDiff only for one function call, everything outside of that is being handled by Zygote. The same is true of most broadcasting operations, now. Are you sure this wouldn't work in your use case?

**Comment by mcabbott** [comment]
Oh maybe I mis-read the question. You might be looking for `Zygote.dropgrad` or `Zygote.ignore` or `Zygote.@nograd`, to hide some side-computation (for printing, etc) from Zygote completely?

**Comment by DavidKoplow** [comment]
Thanks for the help! `Zygote.ignore` did the trick. 

But, could you explain the mixed-mode thing a little more? Let's say I am reverse-differentiating a function `A(x)`, in which `B(x)` and `C(x)` are called. Let's say the pullback of `C` is known but not of `B`. Are you saying that it is possible to automatically calculate the pullback of `B` using forwarddiff then use that with the pullback of `C` to find the gradient of `A`?

**Comment by DhairyaLGandhi** [comment]
You might be interested in looking at `ChainRules.rrule_via_ad` which lets you hook back into ad which is useful for higher order or compositional style functions.

**Comment by mcabbott** [comment]
> it is possible to automatically calculate the pullback of B using forwarddiff then use that with the pullback of C to find the gradient of A?

Yes, that's exactly what it does. With lots of show statements:
```julia
julia> using Zygote, ForwardDiff

julia> using Zygote: @showgrad, forwarddiff

julia> B(b) = (@show b;  @showgrad b);

julia> C(c) = (@show c;  @showgrad c);

julia> A(x) = B(C(x^2) + 10)^2;

julia> Zygote.withgradient(A, 2.0)
c = 4.0
b = 14.0
  # now it's finished the forward pass, starts reverse:
∂(b) = 28.0
∂(c) = 28.0
(val = 196.0, grad = (112.0,))

julia> A2(x) = forwarddiff(B, C(x^2) + 10)^2;

julia> Zygote.withgradient(A2, 2.0)
c = 4.0
b = Dual{Nothing}(14.0,1.0)
∂(c) = 28.0
(val = 196.0, grad = (112.0,))

julia> Zygote.withgradient(A3, 2.0)
c = Dual{Nothing}(4.0,1.0)
b = 14.0
∂(b) = 28.0
(val = 196.0, grad = (112.0,))
```
It has limitations, especially that it assumes the function is pure -- `forwarddiff(f, x)` will only find derivatives with respect to this `x`, if the closes over other parameters it will silently forget about them.

And broadcasting, while here -- this is more careful, and should only use the forward mode when it's sure `f` is pure enough:
```
julia> Zygote.withgradient(x -> sum(B, x), [10,20])
b = 10
b = 20
∂(b) = 1
∂(b) = 1
(val = 30, grad = ([1, 1],))

julia> Zygote.withgradient(x -> sum(B.(x)), [10,20])
b = Dual{Nothing}(10,1)
b = Dual{Nothing}(20,1)
(val = 30, grad = ([1, 1],))
```
