### ISSUE TITLE
Limitations Docs

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#1077]
It's well understood that Zygote doesn't support mutation (particularly of arrays). My recollection was that this features prominently in the docs, but I now can't see where it's mentioned -- certainly it's not obvious. To my mind it's important that we mention this prominently so that new users expectations are set appropriately.

@DhairyaLGandhi would you be open to a PR adding a `Limitations` section to the readme?

**Comment by mcabbott** [comment]
This would be good. 

IMO the "Performance Profiling" section isn't so useful, it would be better to have there a section about making it work at all (and what limitations you may encounter), then making it fast. Of which profiling could be the last section.
