### ISSUE TITLE
_project error

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#1078]
The problem occurs when one tries to take the `Zygote.gradient` of a function an `AbstractArray` with a structural tangent.

`ProjectTo(my_array)` produces a `ProjectTo{AbstractArray}`, and Zygote winds up producing a `Tangent{Any}` for it. This means that [this](https://github.com/JuliaDiff/ChainRulesCore.jl/blob/2ec2549b73b22bc08f554dae864fb650cfb9c3d7/src/projection.jl#L139) method doesn't apply.

MWE:
```julia
julia> using ChainRules: Tangent, ProjectTo, NoTangent

julia> using KernelFunctions: MOInputIsotopicByFeatures

julia> x = MOInputIsotopicByFeatures(randn(3), 2);

julia> dx = Tangent{Any}(x=randn(3), out_dim=NoTangent());

julia> ProjectTo(x)(dx)
ERROR: MethodError: no method matching (::ProjectTo{AbstractArray, NamedTuple{(:elements, :axes), Tuple{Vector{typeof(identity)}, Tuple{Base.OneTo{Int64}}}}})(::Tangent{Any, NamedTuple{(:x, :out_dim), Tuple{Vector{Float64}, NoTangent}}})
Closest candidates are:
  (::ProjectTo{T, D} where D<:NamedTuple)(::Tangent{var"#s15", T} where {var"#s15"<:T, T}) where T at /Users/willtebbutt/.julia/packages/ChainRulesCore/ChM7X/src/projection.jl:139
  (::ProjectTo{AbstractArray, D} where D<:NamedTuple)(::Union{LinearAlgebra.Adjoint{T, var"#s832"}, LinearAlgebra.Transpose{T, var"#s832"}} where {T, var"#s832"<:(AbstractVector{T} where T)}) at /Users/willtebbutt/.julia/packages/ChainRulesCore/ChM7X/src/projection.jl:239
  (::ProjectTo{AbstractArray, D} where D<:NamedTuple)(::Number) at /Users/willtebbutt/.julia/packages/ChainRulesCore/ChM7X/src/projection.jl:245
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1
```

What is the appropriate fix @mcabbott @oxinabox @mzgubic ? I can work around this by using `pullback` or `_pullback` directly, but it's obviously sub-optimal not to be able to use `gradient`.

Where's the discussion about adding the `_project` call [here](https://github.com/FluxML/Zygote.jl/blob/528e0be677d1feb9ccf6fc4ab298f4d8a106de10/src/compiler/interface.jl#L77)? I feel like I've seen it somewhere, but I'm not sure where...

**Comment by DhairyaLGandhi** [comment]
See #1075 

And #1044, definitely agree that that should go. I feel projecting gradients to some space may be limiting in some ways the compiler can optimise code.

**Comment by willtebbutt** [comment]
> I feel projecting gradients to some space may be limiting in some ways the compiler can optimise code.

To be clear, I have no problem whatsoever will projecting things (e.g. dropping the imaginary bit of a complex number representing the tangent of a real number) -- it's both a correctness and performance issue (especially where linear algebra is concerned). I just don't think the implementation is correct here 🤷 .

I would be interested to know where you think projections could get in the way of optimisations because my experience has consistently been that failing to project is the thing that causes problems, but this probably isn't the place for that discussion.

**Comment by mcabbott** [comment]
Should this be a CRC issue? You will get the same error regardless of what rule or function applies the projection. The assumption of projection is that it may be applied widely.

It's likely to `ProjectTo{AbstractArray}` should pass all `Tangent`s through, which is I think what you're arguing should happen.

**Comment by willtebbutt** [comment]
I was hoping you would suggest the appropriate fix :) Sounds like you're in favour of modification to CRC? Happy to open a PR if that's so.

**Comment by oxinabox** [comment]
Possibly Zygote should type-pirate:
```julia
(::ProjectTo)(dx::Tangent}) = dx
```
to work-around the fact that it loses track of primal types
and so it can't manage to hit:
```julia
(::ProjectTo{T})(dx::Tangent{<:T}) where {T} = dx
```

This is what it currently does for Complex numbers for this reason, because it can't hit the `Tangent{<:Complex}` method
https://github.com/FluxML/Zygote.jl/blob/528e0be677d1feb9ccf6fc4ab298f4d8a106de10/src/compiler/chainrules.jl#L151

**Comment by willtebbutt** [comment]
Seems reasonable to me. I'll open a PR.
