### ISSUE TITLE
AD is struggling with ForwardDiff.jacobian

### ISSUE THREAD

**Issue by killah-t-cell** [FluxML/Zygote.jl#1081]
Zygote's AD seems to not be working with the following line in Quadrature.jl:

https://github.com/SciML/Quadrature.jl/blob/f913f39d9766a5d15f3829c51155ab3b655269d3/src/Quadrature.jl#L92

It errors with when I run it with Zygote

```julia
ERROR: LoadError: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{Main.Quadrature.var"#317#321"{Main.Quadrature.var"#v#320"{Vector{Int64}, Vector{Float64}, BitVector, BitVector, BitVector, BitVector}}, Float64}, Float64, 1})
Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  (::Type{T})(::T) where T<:Number at boot.jl:760
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  ...
```

An MWE can be found here https://github.com/SciML/Quadrature.jl/pull/74#issuecomment-927304089

Would appreciate any tips or suggestions for fixes.

**Comment by mcabbott** [comment]
What changed here?

A minimal example which appears to work is:
```
julia> using Zygote, ForwardDiff

julia> Zygote.gradient(x -> det(ForwardDiff.jacobian(x -> sin.(x), x)), [1,2])
([0.35017548837401463, -0.49129549643388193],)

julia> ForwardDiff.gradient(x -> det(ForwardDiff.jacobian(x -> sin.(x), x)), [1,2])
2-element Vector{Float64}:
  0.35017548837401463
 -0.49129549643388193
```
For the far-from-minimal example linked, what we can see of the stack trace shows something writing dual numbers into an array of non-duals, but that describes almost every ForwardDiff problem -- it's hard to guess the cause, please post the complete stack trace somewhere, even if its usefulness isn't clear to you.

**Comment by killah-t-cell** [comment]
Yeah it was an user error. It is why I closed the issue :) thanks for the help in any case though.
