### ISSUE TITLE
`Dict`s in struct fields don't propagate gradients

### ISSUE THREAD

**Issue by SBuercklin** [FluxML/Zygote.jl#1115]
If we insert a `Dict` into a struct field and do some calculations with that `Dict`, we get a `nothing` derivative with respect to that field. 

Example is on `0.6.29`. I included a second field to show that gradients still accumulate for the other fields.
```julia
struct Container
    x
    y
end
f_dict(d,y) = d[:a]^2 + y^3
f_container(c) = c.x[:a]^2 + c.y^3

d = Dict(:a => 3)
c = Container(d, 4.0)

Zygote.gradient(f_dict, d, 4.0)
# (Dict{Any, Any}(:a => 6.0), 48.0)

Zygote.gradient(f_container, c)
# ((x = nothing, y = 48.0),)

```

**Comment by SBuercklin** [comment]
Duplicate of #717

**Comment by CarloLucibello** [comment]
@SBuercklin we have many Dict-related issues
https://github.com/FluxML/Zygote.jl/labels/dictionary
I suggest to use NamedTuple instead of dictionary whenever possible
