### ISSUE TITLE
Hessian Vector Products

### ISSUE THREAD

**Issue by RS-Coop** [FluxML/Zygote.jl#1141]
Given a function ``f``, with Hessian ``H``, I am trying to compute matrix free Hessian vector products ``Hv``. Currently, I can accomplish this using ForwardDiff and Zygote in the following function:
```julia
function _hvp(f, x, v)
	g = x -> Zygote.gradient(f,x)[1]
	ForwardDiff.partials.(g(ForwardDiff.Dual{hvp}.(x,v)), 1)
end
```
Now specifically consider the situation where ``f`` maps to a scalar, e.g. a neural network. I have two questions related to all of this. First, I know that forward-over-back AD is theoretically the best way to compute these HVPs, but do you have any reccomendations for the best approach to this? Second, I will be doing repeated HVPs with the same Hessian ``H``. The approach above seems inefficient for this in the sense that it recomputes the gradient each time. Is it possible to compute the gradient once using backward mode AD, and then use forward mode AD each time I want to compute a HVP with a new right hand side?

Maybe this second ask isn't possible in the forward-over-back regime, but it could be using backward-over-back?

Thanks for all the help!

**Comment by cossio** [comment]
Did you find an answer for your question?

**Comment by RS-Coop** [comment]
No not entirely. I just decided that maybe this wasn't the best place to ask., but if you have any thoughts or suggestions I would welcome them!
