### ISSUE TITLE
Unable to differentiate through Einstein sums from Einsum.jl -- Mutating arrays is not supported

### ISSUE THREAD

**Issue by harwiltz** [FluxML/Zygote.jl#1164]
Below is a minimal example of an exception thrown by Zygote when trying to compute a gradient through an Einstein summation from Einsum.jl. I thought Einsum.jl was a fairly standard library, but I'm no longer sure that's the case. Other than this issue though, it is the most elegant Einsum I've found.

```julia
julia> using Einsum

julia> using LinearAlgebra

julia> using Zygote

julia> function loss(x)
       @einsum l[i] := x[i]
       norm(x)
       end
loss (generic function with 1 method)

julia> gradient(loss, [3., 4.])
ERROR: Mutating arrays is not supported -- called setindex!(::Vector{Float64}, _...)
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] (::Zygote.var"#442#443"{Vector{Float64}})(#unused#::Nothing)
   @ Zygote ~/.julia/packages/Zygote/FPUm3/src/lib/array.jl:71
 [3] (::Zygote.var"#2339#back#444"{Zygote.var"#442#443"{Vector{Float64}}})(Δ::Nothing)
   @ Zygote ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67
 [4] macro expansion
   @ ~/.julia/packages/Einsum/AVMOj/src/Einsum.jl:278 [inlined]
 [5] Pullback
   @ ./REPL[4]:2 [inlined]
 [6] (::typeof(∂(loss)))(Δ::Float64)
   @ Zygote ~/.julia/packages/Zygote/FPUm3/src/compiler/interface2.jl:0
 [7] (::Zygote.var"#57#58"{typeof(∂(loss))})(Δ::Float64)
   @ Zygote ~/.julia/packages/Zygote/FPUm3/src/compiler/interface.jl:41
 [8] gradient(f::Function, args::Vector{Float64})
   @ Zygote ~/.julia/packages/Zygote/FPUm3/src/compiler/interface.jl:76
 [9] top-level scope
   @ REPL[5]:1
```

**Comment by mcabbott** [comment]
This won't work, unfortunately. Einsum.jl works by allocating an output array, and then [writing into it in a loop](https://github.com/ahwillia/Einsum.jl#what-happens-under-the-hood), which is something Zygote can't handle. It will work with ForwardDiff.jl, and thus with `gradient(x -> Zygote.forwarddiff(loss, x), [3., 4.])` will work.

But several newer packages will explicitly handle derivatives. Mine is [Tullio.jl](https://github.com/mcabbott/Tullio.jl), but [OMEinsum.jl](https://github.com/under-Peter/OMEinsum.jl) does this too, and [TensorRules.jl](https://github.com/ho-oto/TensorRules.jl) builds on TensorOperations.jl.

**Comment by harwiltz** [comment]
@mcabbott Thanks for the explanation and the suggestions! Much appreciated.
