### ISSUE TITLE
Pullback evaluates to nothing for broadcasted distribution operations (regression)

### ISSUE THREAD

**Issue by oschulz** [FluxML/Zygote.jl#1178]
For

```julia
using Zygote, Distributions

function f(x)
    ds = Poisson.(x)
    mean.(ds)
end

x = rand(100)
dy = rand(length(f(x)))
```

Zygote v0.6.35 and master give

```julia
julia> Zygote.pullback(f, x)[2](dy)
(nothing,)
```

This used to work, Zygote v0.6.34 returns the correct result

```julia
julia> Zygote.pullback(f, x)[2](dy)
([0.25510267258178587, ...],)
```

(Me and @apmypb stumbled over this in an MGVI.jl application that stopped working after a package update.)

**Comment by mcabbott** [comment]
Probably https://github.com/FluxML/Zygote.jl/pull/1171 is too broad, sorry!

**Comment by oschulz** [comment]
Thanks a lot for the super-quick fix, @mcabbott , MGVI.jl works again. :-)
