### ISSUE TITLE
Function mod2pi + list of implemented functions

### ISSUE THREAD

**Issue by petvana** [FluxML/Zygote.jl#118]
I found that function `mod2pi` is not implemented yet, but `mod` works. Is there any list of implemented functions? Minimal working example is:

```
using Zygote

# This is working
gradient(x -> mod(x, 2pi), 1.)

# This is not
gradient(x -> mod2pi(x), 1.)
```

**Comment by mcabbott** [comment]
If I'm not mistaken, `mod` is coming from here:  
https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl#L95

There's a `rem2pi` but no `mod2pi`, but perhaps easy to add?

**Comment by MikeInnes** [comment]
Yeah, these could be added to DiffRules or straight to Zygote in [this file](https://github.com/FluxML/Zygote.jl/blob/ac755a794d58215b66ea9da2f767fc200e0ecb6a/src/lib/real.jl).

**Comment by Moelf** [comment]
this issue can be closed now?
