### ISSUE TITLE
Unexpected error with using the `normalize` from LinearAlgebra

### ISSUE THREAD

**Issue by ntausend** [FluxML/Zygote.jl#1190]
Hey, I recently stumbled across this hard to debug problem. The problem is that having a function using the `normalize` function from the LinearAlgebra package which takes some AbstractArray and return the normalized version leads to a 
```
ERROR: Mutating arrays is not supported -- called setindex!(::Matrix{Float64}, _...)
```
error. I guess the problem boils down to LinearAlgebra internally using the `__normalize!(...)` function which scales an array 
in-place by its norm. However, this is not obvious from the documentation making debugging hard. I hope this is the correct place for this issue.

Minimal example reproducing this error in Julia 1.7.2:
```
using Zygote
using LinearAlgebra

function fn(A)
    B = normalize(A)
    c = norm(B*B)
     return c
end

A = rand(2,2)
gradient(fn, A) |> display
```

**Comment by mcabbott** [comment]
There are rules for `normalise` here: https://github.com/JuliaDiff/ChainRules.jl/blob/main/src/rulesets/LinearAlgebra/norm.jl#L257
but they seem to only handle vectors not matrices, perhaps they can just be generalised.
```julia
julia> gradient(x -> sum(normalize(x)), [1,2,3])
([0.1527207096642425, 0.03818017741606061, -0.07636035483212128],)

julia> gradient(x -> sum(normalize(x)), [1 2; 3 4])
ERROR: Mutating arrays is not supported -- called setindex!(::Matrix{Float64}, _...)

  [9] (::typeof(∂(__normalize!)))(Δ::FillArrays.Fill{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}})
    @ Zygote ~/.julia/packages/Zygote/cCyLF/src/compiler/interface2.jl:0
 [10] Pullback
    @ ~/.julia/dev/julia/usr/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1787 [inlined]
 [11] (::typeof(∂(normalize)))(Δ::FillArrays.Fill{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}})
```

**Comment by ntausend** [comment]
Thank you for the reply and sorry for the late response. Yes seems to be right. Thanks for pointing that out.
