### ISSUE TITLE
Params iteration is type unstable

### ISSUE THREAD

**Issue by ancapdev** [FluxML/Zygote.jl#1202]
https://github.com/FluxML/Zygote.jl/commit/df762eb8236008d970c2c9fceba4df7993ec59ac, fixing #941, removed the type specification on `Params.order`, which means the forwarded methods like `iterate`, `getindex`, and `length` are subject to type instability, dynamic dispatch, and allocations. This hits `Flux.update!()`.

I'm trying to understand why this specification was removed and what can be done to resolve it?

**Comment by ToucheSir** [comment]
Looks the the addition of [this constructor](https://github.com/FluxML/Zygote.jl/blob/882a939986871d834b98b3cbbf2fab4bba6183ff/src/compiler/interface.jl#L140) meant that using `Any` was no longer valid. It's not exactly clear to me why we needed the array constructor (Flux doesn't use it), but removing it would be difficult now that there are documentation examples referencing it.

One path for restoring type stability might be to give `Params` an eltype type param. Then you could write:
```julia
struct Params{T}
  order::Buffer{T, Vector{T}}
  params::IdSet{T}
end
```
Where `T` would be `Any` under most circumstances.

**Comment by ancapdev** [comment]
Or maybe more general, so that `Buffer` can change in implementation and `xs` can be of type other than `Vector`?
```Julia
struct Params{B <: Buffer}
  order::B
  params::IdSet{T}
end
```

**Comment by ToucheSir** [comment]
Where does T  come from here? We don't want to over-specialize the struct unless absolutely necessary. That and Flux is moving off implicit params in the not so distant future (the groundwork for this has already started with v0.13).

**Comment by ancapdev** [comment]
> Where does T come from here? We don't want to over-specialize the struct unless absolutely necessary. That and Flux is moving off implicit params in the not so distant future (the groundwork for this has already started with v0.13).

Sorry, I meant to leave `params` as-is, so:
```Julia
struct Params{B <: Buffer}
  order::B
  params::IdSet{Any}
end
```

**Comment by ToucheSir** [comment]
Looks reasonable to me, happy to take a PR for this.
