### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Zygote.jl#129]
Minimal test case for the crash seen in #124.

```julia
using Zygote

foo = function ()
    if false
        if false
            return
        end
    end
    for I in ()
    end
end

y, back = forward(foo)

back(nothing)

```

**Comment by MikeInnes** [comment]
Fixed with an extra `compact!` in the right place. Basically we'd delete a phi node by setting that statement to `nothing`, and the phi node after it was no longer picked up by slot conversion (since it wasn't at the beginning of the block). The first compaction didn't fix this but a second one picks it up.

**Comment by Keno** [comment]
> since it wasn't at the beginning of the block

FWIW, it is legal IR to have a `nothing` in front of a PHI node, so things that look for phi nodes should skip them.

**Comment by MikeInnes** [comment]
That seems like it'd be a good idea, although I realised my explanation above can't be the whole story since we [already call compact here](https://github.com/FluxML/Zygote.jl/commit/89ba76bccc51b5da44067d3595107cc15e09dbd8#diff-7e30a6cf341607b4ae121b3fcae2e020R434) later on. Presumably there's a better solution here than "compact the IR 4 times" but it's not obvious in which cases `compact!` isn't idempotent.
