### ISSUE TITLE
extremely slow compilation of gradient AND compilation error (two bugs, really)

### ISSUE THREAD

**Issue by tmbdev** [FluxML/Zygote.jl#1292]
```julia
function dist4(x, y)
    @tullio (max) hi[i, j] := abs(x[k, i] - y[k, j]);
    @tullio result[i, j] := exp(2*(abs(x[k, i] - y[k, j]) - hi[i, j]));
    # @tullio result[i, j] += log(2*hi[i, j]); # ***
    return result
end
... allocate GPU arrays for a, b, and Δresult ...
@time r, g = Zygote.pullback(dist4, a, b)
@time Δa, Δb = g(Δresult);
```

PROBLEM 1

The first run of the gradient computation takers **404 seconds**, which is way too long for such a simple function. 

(The `Zygote.pullback` call takes 17 seconds, which is also pretty slow.)

The second run is fast, so it's somehow the compilation that's the problem.

PROBLEM 2

When the marked line in `dist4` is uncommented, the compilation fails completely, saying that `try/catch is not supported`. I suspect that's due to the log function and the (hypothetical) possibility of negative values.

Full code, Manifest, output is here: https://gist.github.com/dfd6e51f23054c2acfc151d99d115a5a

**Comment by mcabbott** [comment]
No bright ideas about problem 1, but problem 2 shouldn't work. It's an in-place update of an array, which Zygote forbids, and for which Tullio does not generate a gradient. 

I get some error from Zygote attempting to differentiate some other part, not exactly sure why, I thought this was supposed to give a friendly error instead. 
```
julia> @time r, g = Zygote.pullback(dist4, a, b)
ERROR: MethodError: no method matching one(::UnitRange{Int64})
...
  [1] (::ChainRules.var"#1700#1702"{typeof(ChainRulesCore.frule), Zygote.ZygoteRuleConfig{Zygote.Context{false}}, typeof(length)})(a::UnitRange{Int64})
    @ ChainRules ~/.julia/packages/ChainRules/DUopG/src/rulesets/Base/broadcast.jl:109
  [2] map
    @ ./tuple.jl:274 [inlined]
  [4] unzip_broadcast(f::ChainRules.var"#1700#1702"{typeof(ChainRulesCore.frule), Zygote.ZygoteRuleConfig{Zygote.Context{false}}, typeof(length)}, args::Tuple{UnitRange{Int64}, UnitRange{Int64}})
    @ ChainRules ~/.julia/packages/ChainRules/DUopG/src/unzipped.jl:41
  [5] split_bc_inner(frule_fun::typeof(ChainRulesCore.frule), cfg::Zygote.ZygoteRuleConfig{Zygote.Context{false}}, f::typeof(length), arg::Tuple{UnitRange{Int64}, UnitRange{Int64}})
    @ ChainRules ~/.julia/packages/ChainRules/DUopG/src/rulesets/Base/broadcast.jl:108
  [6] split_bc_forwards(cfg::Zygote.ZygoteRuleConfig{Zygote.Context{false}}, f::typeof(length), arg::Tuple{UnitRange{Int64}, UnitRange{Int64}})
    @ ChainRules ~/.julia/packages/ChainRules/DUopG/src/rulesets/Base/broadcast.jl:105
  [7] rrule(cfg::Zygote.ZygoteRuleConfig{Zygote.Context{false}}, #unused#::typeof(Base.Broadcast.broadcasted), #unused#::Base.Broadcast.Style{Tuple}, f::typeof(length), args::Tuple{UnitRange{Int64}, UnitRange{Int64}})
    @ ChainRules ~/.julia/packages/ChainRules/DUopG/src/rulesets/Base/broadcast.jl:41
```

**Comment by tmbdev** [comment]
Thanks, Problem 2 is solved by removing the in-place update; a more user-friendly error message would be nice; after all, detecting the presence of an in-place update is trivial in such cases.

I don't see why you are getting that error on the pullback. Are you using the packages from my Manifest? I had other problems with Tullio+Zygote before, but they seem to have gone away in 1.8 and after package updates.

**Comment by mcabbott** [comment]
No I just tried on my laptop, everything latest. [This line](https://github.com/mcabbott/Tullio.jl/blob/master/src/eval.jl#L52) is meant to be the (moderately) friendly error.

**Comment by ToucheSir** [comment]
I was able to run the MWE locally, but only but removing 2 zeros from `d`, `m`, and `n`. I learned this the hard way because my GPU immediately OOMed and killed my desktop environment. Given that the pullback runs in ~5s with the reduced dims size, pretty sure this is not a slow compilation issue on Zygote's end.

**Comment by tmbdev** [comment]
OK, that's quite weird, but at least it's a workaround: if the initial invocation is with small arrays, the compilation is fast, and afterwards, it runs fast on large arrays as well.

Nevertheless, the long Zygote.pullback invocation is unexpected; it might still be a good idea to try to figure out what the cause is; it seems to me kernel compilation times should not depend on the size of the arrays passed to the kernel upon first compilation..

**Comment by tmbdev** [comment]
For PROBLEM 2, I would suggest testing for common cases of in-place modification (e.g., use of `+=` etc.) and raising an explicit error, rather than letting it fail deeper down with a "no gradient" message.

**Comment by mcabbott** [comment]
In-place use is explicitly supported, only within a gradient will it not work. 

I agree the error could be made more friendly (after being made to work at all...). In some other cases `verbose=true` tells you more about the problem; maybe this case should too:
```
julia> @tullio result[i, j] := mylog(2*hi[i, j]) verbose=true;
┌ Warning: symbolic gradient failed
│   err = "no diffrule found for function mylog(_)."
└ @ Tullio ~/.julia/packages/Tullio/wAFFh/src/macro.jl:1264
```

**Comment by ToucheSir** [comment]
> Nevertheless, the long Zygote.pullback invocation is unexpected; it might still be a good idea to try to figure out what the cause is; it seems to me kernel compilation times should not depend on the size of the arrays passed to the kernel upon first compilation..

Compilation times do not. Note how your output in the gist shows 0.76% of the 404s is compilation time, so only 3 seconds. The rest I can't speak to.

**Comment by tmbdev** [comment]
Well, the number given can't be correct, since execution time of the compiled kernel is a fraction of a second. Pretty much by definition, everything that isn't kernel execution is some form of compilation. Furthermore, since the really long compilation times only happen with Zygote.pullback, it must be some interaction between the Zygote output and the KernelAbstraction kernel compiler that produces this result.

**Comment by ToucheSir** [comment]
I multiplied all sizes by 10 and get much the same times. Multiplying by 20 (max my GPU can support) leads to a drastically increased time, so it would appear some pathological case is being hit.

However, the majority of time appears to be coming from GPUArrays and Tullio rather than the AD. Looking at a PProf profile, most of the time is spent on the other side of https://github.com/mcabbott/Tullio.jl/blob/v0.3.4/src/eval.jl#L49, where Zygote isn't involved at all. This in turn spends most of its time in https://github.com/JuliaGPU/KernelAbstractions.jl/blob/v0.8.3/lib/CUDAKernels/src/CUDAKernels.jl#L273, i.e. compiling and launching the generated kernel.

So I suspect two things. Firstly, you should be able to replicate this issue without Zygote using ChainRulesCore alone. The only reason I haven't done so already is because I don't know how to coax Tullio to return an `Eval` :). Secondly, the definitely compilation but not reported as compilation time you're seeing is from GPU kernel compilation. PProf tells me most of this time is spent in LLVM. Here it would help to interrogate the generated kernel for the backwards pass to see if something is being unnecessarily unrolled or what have you.

**Comment by mcabbott** [comment]
With some luck https://gist.github.com/mcabbott/66388d37f52797d0b52c61d1ebf189df might be the first call above, just the CUDA bit.

**Comment by tmbdev** [comment]
OK, well as far as I'm concerned, the workaround of running a small instance is good enough for my needs; the discussion has been very helpful.

However, the fact that the compilation time in some part of the toolchain is massively dependent on the actual dimensions of a data array suggests to me that there is a problem somewhere. Maybe I should submit a bug report to KernelAbstractions.

(Thanks for the benchmarking and profiling; I tried getting at that with @profile, but hard a hard time reading the profiler output. I'll give PProf a try.)

**Comment by tmbdev** [comment]
I'll make this closed for now since there is a workaround and since the problem isn't obviously in Zygote.
