### ISSUE TITLE
Not able to @opt_out rules with RuleConfig

### ISSUE THREAD

**Issue by tansongchen** [FluxML/Zygote.jl#1342]
Let's say I have a type `WeirdNumber <: Number` is so weird that I don't want its derivative of power function (`^`) be calculated by `rrule` of `^` and `literal_pow`, and should instead go through and differentiate its definition. Since Zygote defines AD-specific rules for `literal_pow` with `RuleConfig` in its code base, I had to also `@opt_out` this rule. However, the following MWE didn't work:

```julia
using ChainRulesCore: @opt_out, RuleConfig
import Base: ^

struct WeirdNumber <: Number
    a::Float64
end

^(x::WeirdNumber, p::Int) = WeirdNumber(x.a ^ p)

@opt_out rrule(::typeof(Base.literal_pow), ::typeof(^), x::WeirdNumber, ::Val{p}) where {p}
@opt_out rrule(::RuleConfig, ::typeof(Base.literal_pow), ::typeof(^), x::WeirdNumber,
               ::Val{p}) where {p}

using Zygote

fun(x::WeirdNumber) = (x^4).a

gradient(fun, WeirdNumber(2.))
```

Error:

```
ERROR: type Nothing has no field method
Stacktrace:
  [1] getproperty(x::Nothing, f::Symbol)
    @ Base ./Base.jl:38
  [2] has_chain_rrule(T::Type)
    @ Zygote ~/.julia/packages/Zygote/SmJK6/src/compiler/chainrules.jl:21
  [3] #s2948#1074
    @ ~/.julia/packages/Zygote/SmJK6/src/compiler/interface2.jl:20 [inlined]
  [4] var"#s2948#1074"(::Any, ctx::Any, f::Any, args::Any)
    @ Zygote ./none:0
  [5] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:582
  [6] _pullback
    @ ~/Applications/project/TaylorDiff.jl/.vscode/opt_lit_pow.jl:16 [inlined]
  [7] _pullback(ctx::Zygote.Context{false}, f::typeof(fun), args::WeirdNumber)
    @ Zygote ~/.julia/packages/Zygote/SmJK6/src/compiler/interface2.jl:0
  [8] pullback(f::Function, cx::Zygote.Context{false}, args::WeirdNumber)
    @ Zygote ~/.julia/packages/Zygote/SmJK6/src/compiler/interface.jl:44
  [9] pullback
    @ ~/.julia/packages/Zygote/SmJK6/src/compiler/interface.jl:42 [inlined]
 [10] gradient(f::Function, args::WeirdNumber)
    @ Zygote ~/.julia/packages/Zygote/SmJK6/src/compiler/interface.jl:96
```

**Comment by oxinabox** [comment]
Oh weird. This is definitely a bug. I am on vacation for next few weeks. And don't know when exactly I will have time to look into it.
If someone else wants to dig feel encouraged.
If not I will try to attend to it when I get back.

**Comment by oxinabox** [comment]
Hmm.
some proposed solutions

### sol0
Just give informative ambiguity error if If `meta(...)` returns `nothing`

### sol1
 If `meta(...)` returns `nothing`,
we assume that there is an ambiguity (or other problem with the rrule) and fallback to a sensible default behaviour of ignoring the rule and doing AD.

This solved this case, since goal is to ignore the rule.
The problem with this is that missed rules can lead to slow code and no sign that this is occurring.
I don't think we can even emit a debug log here as it's in the generating part of a generated function. (So only `Core.println` works)

### sol2
There might be an alternative solution where we only do this if there is an `no_rrule` that would be in the ambig pool. (And otherwise give an informative error message)
Which would mean there is an extra rule to remember: opt out wins if ambiguity.

I am not sure if this is logically sound.

**Comment by ToucheSir** [comment]
> I don't think we can even emit a debug log here as it's in the generating part of a generated function. (So only `Core.println` works)

We could add a param to the context which controls whether the fallback is allowed or an error is thrown. I agree that this feels suboptimal though.

Sol2 could be narrowed to if there is a `no_rrule` with a `RuleConfig >: MyADRuleConfig`. Then if the AD authors really believe they have a better manual rule, they can choose one of taking the opting out package as a (weak) dep or upstreaming their rule. That said, one could make a similar argument for the reverse, where downstream libraries take a weak dep on the AD. It's unfortunate that we can't indicate somehow that the RuleConfig is less important for dispatch than the actual args in case of ambiguity&mdash;a language-level fix would be most elegant.

**Comment by oxinabox** [comment]
>  To me this ambiguity sounds like a design problem to ChainRulesCore.jl, since for any AD system, the coexistence of "RuleConfig + Specific Type" method by user and "XXXRuleConfig + Generic Type" by AD author will cause an ambiguity.

I mean, it's a real ambiguity. There is no definite right way to handle it.
Those who prefer an AD that is always fast but sometimes errors would like this to just error **sol 0**
Those who prefer AD always works would prefer **sol 1**
so it should be up the the preference of the AD, not ChainRulesCore.

**Comment by oxinabox** [comment]
I am inclined to open a PR with **Sol 1**, because it seems easy enough to implement,
and we can upgrade it to **Sol 2** or similar later.

**Comment by oxinabox** [comment]
I think that is fine. If you update to Julia 1.9 you can make it a weak dependency.
