### ISSUE TITLE
Type instability in Flux.gradient with immutable structs

### ISSUE THREAD

**Issue by PatMcFarlane** [FluxML/Zygote.jl#1368]
I've been working on replicating using Julia/Flux an economics application of deep learning [here](https://notes.quantecon.org/submission/5ddb3c926bad3800109084bf).

I ran into type instability issues when using immutable structs to house parameters.   The below code is a minimal example to highlight the issue:

```
using Flux

struct TestParas
    expon::Float64
end

TP = TestParas(2.0)

mod1 = Dense(2,1)

function DataGen1(model, TP)

    data = ones(2)

    resid = sum(model(data).^TP.expon)

    return resid

end

#check to make sure the gradient is working correctly
grads = Flux.gradient(m -> DataGen1(m,TP), mod1)

@code_warntype Flux.gradient(m -> DataGen1(m,TP), mod1)
```

The output looks like this:
```
MethodInstance for Zygote.gradient(::var"#7#8", ::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})
  from gradient(f, args...) in Zygote at C:\Users\Patrick\.julia\packages\Zygote\g2w9o\src\compiler\interface.jl:95
Arguments
  #self#::Core.Const(Zygote.gradient)
  f::Core.Const(var"#7#8"())
  args::Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}}
Locals
  @_4::Int64
  grad::Union{Nothing, Tuple}
  back::Zygote.var"#60#61"
  y::Any
Body::Union{Nothing, Tuple{Any}}
1 ─ %1  = Core.tuple(f)::Core.Const((var"#7#8"(),))
│   %2  = Core._apply_iterate(Base.iterate, Zygote.pullback, %1, args)::Tuple{Any, Zygote.var"#60#61"}
│   %3  = Base.indexed_iterate(%2, 1)::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(2)])
│         (y = Core.getfield(%3, 1))
│         (@_4 = Core.getfield(%3, 2))
MethodInstance for Zygote.gradient(::var"#9#10", ::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})      
  from gradient(f, args...) in Zygote at C:\Users\Patrick\.julia\packages\Zygote\g2w9o\src\compiler\interface.jl:95
Arguments
  #self#::Core.Const(Zygote.gradient)
  f::Core.Const(var"#9#10"())
  args::Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}}
Locals
  @_4::Int64
  grad::Union{Nothing, Tuple}
  back::Zygote.var"#60#61"
  y::Any
Body::Union{Nothing, Tuple{Any}}
1 ─ %1  = Core.tuple(f)::Core.Const((var"#9#10"(),))
│   %2  = Core._apply_iterate(Base.iterate, Zygote.pullback, %1, args)::Tuple{Any, Zygote.var"#60#61"}
│   %3  = Base.indexed_iterate(%2, 1)::Core.PartialStruct(Tuple{Any, Int64}, Any[Any, Core.Const(2)])
│         (y = Core.getfield(%3, 1))
│         (@_4 = Core.getfield(%3, 2))
│   %6  = Base.indexed_iterate(%2, 2, @_4::Core.Const(2))::Core.PartialStruct(Tuple{Zygote.var"#60#61", Int64}, Any[Zygote.var"#60#61", Core.Const(3)])
│         (back = Core.getfield(%6, 1))
│   %8  = Zygote.sensitivity(y)::Any
│         (grad = (back)(%8))
│   %10 = Zygote.isnothing(grad)::Bool
└──       goto #3 if not %10
2 ─       return Zygote.nothing
3 ─ %13 = Zygote.map(Zygote._project, args, grad::Tuple)::Tuple{Any}
└──       return %13
```

Declaring the parameter ```expon``` in global scope and passing into the ```DataGen1``` function or declaring it as a ```const``` and leaving that out of the function arguments fixes the problem.  But this approach would be quite inconvenient for more involved applications where there are lots of parameters that might need to be changed frequently.

I'm a novice when it comes to Julia and Flux so apologies in advance if this is some kind of coding error or bad practice.

Also, I wasn't sure whether to start an issue here or in Flux.jl.  Happy to move it if appropriate.

Thanks!

**Comment by ToucheSir** [comment]
Thankfully, there are a few ways around this. The easiest is to declare `TP` as `const`. Then you get to keep your parameters co-located. Next easiest is to declare `TP` in a non-global context. This could be in a function or using `let`:
```julia
let TP = TestParas(2.0)
#check to make sure the gradient is working correctly
grads = Flux.gradient(m -> DataGen1(m,TP), mod1)

@code_warntype Flux.gradient(m -> DataGen1(m,TP), mod1)
end
```
Generally speaking, following the advice in the Julia Performance Tips and elsewhere to avoid non-const globals will ensure type stability is maintained here.

**Comment by PatMcFarlane** [comment]
> Generally speaking, following the advice in the Julia Performance Tips and elsewhere to avoid non-const globals (which I presume you'll do naturally even when Flux isn't involved if you're looking for type instabilities) will ensure type stability is maintained here.

Is declaring an instance of a struct in a global context and then passing it to a function considered a non-constant global?   I always thought the problem occurs when people try to use a non-constant global variable in order to avoid the need pass it as a function argument.

Either way, using ```const```  is an easy fix.  

Thanks so much for the suggestion!

**Comment by ToucheSir** [comment]
It's not passed to a function though, but captured in a closure. Namely `m -> DataGen1(m,TP)`. What happens inside the body of `m -> ...` doesn't matter. This is a common source of type instabilities when working in the REPL.

**Comment by PatMcFarlane** [comment]
> It's not passed to a function though, but captured in a closure. Namely `m -> DataGen1(m,TP)`. What happens inside the body of `m -> ...` doesn't matter. This is a common source of type instabilities when working in the REPL.

Thanks!  Learn something new about Julia every time I start a new project.
