### ISSUE TITLE
ERROR: LoadError: ArgumentError: Package Colors [5ae59095-9a9b-59fe-a467-6f913c188581] is required but does not seem to be installed

### ISSUE THREAD

**Issue by chengchingwen** [FluxML/Zygote.jl#1395]
I'm getting a LoadError error when using Zygote complaining about not have Colors installed. Might due to #1390 but I have not idea how it work.

**Comment by CarloLucibello** [comment]
Which julia version? Can you reproduce in a new environment (e.g. with `using Pkg; Pkg.activate(temp=true)`)?

**Comment by chengchingwen** [comment]
On 1.9, but looks like I somehow mess up the manifest.
