### ISSUE TITLE
@adjoint for logabsdet duplicates ChainRules rrule

### ISSUE THREAD

**Issue by ElOceanografo** [FluxML/Zygote.jl#1431]
In [this issue](https://github.com/JuliaDiff/ChainRules.jl/issues/719) (trying to sort out how to do reverse-mode AD for the `logabsdet` of sparse matrices), it was pointed out that [Zygote's `@adjoint ` for `logabsdet`](https://github.com/FluxML/Zygote.jl/blob/e2d7839a476fc1cda407500d9a2ca125bd6e2aa5/src/lib/array.jl#L379) duplicates and overrides [an `rrule` in ChainRules](https://github.com/JuliaDiff/ChainRules.jl/blob/11c230cdf0f37a4f42de909d6c1f8500d1a80d69/src/rulesets/LinearAlgebra/dense.jl#L170). Would it make sense to delete that rule here and let ChainRules handle it?

**Comment by ToucheSir** [comment]
I'd say go for it. If tests pass it should be an easy merge.
