### ISSUE TITLE
Adjoint of Adjoint with NamedTuples

### ISSUE THREAD

**Issue by cortner** [FluxML/Zygote.jl#1438]
Related to #953  and #820 ?

My problem arises in the following context: `model(x, ps)` is a parameterized model.  The loss to estimate parameters involves the x-gradient of the model. When I use Zygote sufficiently carefully - in particular supply hand-coded `rrule` for all model pieces, I am able to do this.

However, I recently switched to using `NamedTuple`s to store parameters (`Lux.jl`) and I now get an error that I don't understand.  The following script should demonstrate this. I would be very grateful for a workaround, or suggestions how to fix this bug if it is something I can  realistically contribute to Zygote myself.

```julia
using LinearAlgebra, Zygote

# define trivial model parameters as vector or as NamedTuple
model(x::AbstractVector, W::AbstractVector) = dot(x, W)
model(x::AbstractVector, ps::NamedTuple) = model(x, ps.W)

N = 5   # size of the problem 
ps0 = ( W = randn(N), )    # params as NamedTuple
x0 = randn(N)            # input 

# gradient w.r.t. state
grad_model(x, W::AbstractVector) = Zygote.gradient( _x -> model(_x, W), x )[1] 
grad_model(x, ps::NamedTuple) = Zygote.gradient( _x -> model(_x, ps), x )[1] 

# define a trivial scalar function of the gradient `p -> dot(a0, grad_model(x0, p))`
# and try to differentiate it. 
a0 = randn(N)

# this works 
try 
   L_W = _W -> dot(a0, grad_model(x0, _W))
   Zygote.gradient(L_W, ps0.W)[1]
   @info("Version 1: ok")
catch 
end

# this also works 
try 
   L_ps1 = _ps -> dot(a0, grad_model(x0, _ps.W))
   Zygote.gradient(L_ps1, ps0)[1]
   @info("Version 2: ok")
catch
end

# but this doesn't
try 
   L_ps2 = _ps -> dot(a0, grad_model(x0, _ps))
   Zygote.gradient(L_ps2, ps0)[1]
   @info("Version 3: ok")
catch e
   @info("Version 3: failed")
   # throw(e)
end
```

This suggests that Zygote cannot backpropagate twice through the `ps.W` ?. It is slightly odd though since it doesn't actually have to do this as I am taking a mixed second derivative.

I've tested this on Julia 1.9.2 and latest Zygote as well as Zygote@0.6.62.

**Comment by cortner** [comment]
Here is the start of the stack trace. The total stack-trace is enourmous.
```
ERROR: Can't differentiate boundscheck expression $(Expr(:boundscheck)).
You might want to check the Zygote limitations documentation.
https://fluxml.ai/Zygote.jl/latest/limitations

Stacktrace:

top-level scope at /Users/ortner/gits/mitacs23/2023MitacsDV/co_doublebackprop/simple3.jl
ERROR: Can't differentiate boundscheck expression $(Expr(:boundscheck)).
You might want to check the Zygote limitations documentation.
https://fluxml.ai/Zygote.jl/latest/limitations

Stacktrace:

error(s::String) at ./error.jl

Pullback at ./essentials.jl

(::Zygote.Pullback{Tuple{typeof(getindex), Core.SimpleVector, Int64}, Tuple{Zygote.Pullback{Tuple{typeof(Core._svec_ref), Bool, Core.SimpleVector, Int64}, Tuple{typeof(Core._svec_ref)}}}})(Δ::Nothing) at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/interface2.jl

Pullback at /Users/ortner/.julia/packages/Zygote/JeHtr/src/tools/builtins.jl

(::Zygote.Pullback{Tuple{typeof(Zygote.literal_getindex), Core.SimpleVector, Val{2}}, Tuple{Zygote.Pullback{Tuple{typeof(getindex), Core.SimpleVector, Int64}, Tuple{Zygote.Pullback{Tuple{typeof(Core._svec_ref), Bool, Core.SimpleVector, Int64}, Tuple{typeof(Core._svec_ref)}}}}}})(Δ::Nothing) at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/interface2.jl

Pullback at ./reflection.jl

(::Zygote.Pullback{Tuple{typeof(fieldcount), Type{NamedTuple{(:W,), Tuple{Vector{Float64}}}}}, Any})(Δ::Nothing) at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/interface2.jl

Pullback at /Users/ortner/.julia/packages/ChainRulesCore/0t04l/src/tangent_types/tangent.jl

(::Zygote.Pullback{Tuple{typeof(ChainRulesCore.canonicalize), ChainRulesCore.Tangent{NamedTuple{(:W,), Tuple{Vector{Float64}}}, NamedTuple{(:W,), Tuple{Vector{Float64}}}}}, Any})(Δ::Nothing) at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/interface2.jl

Pullback at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/chainrules.jl

Pullback at /Users/ortner/.julia/packages/Zygote/JeHtr/src/compiler/chainrules.jl

```

**Comment by ToucheSir** [comment]
I don't think this is related to either linked issue, but here is the line which results in a `boundscheck` expression when differentiated: https://github.com/FluxML/Zygote.jl/blob/master/src/tools/builtins.jl#L12. My somewhat fragmentary understanding is that `getindex` recently changed in Base to use `@inbounds` in some paths and this may be throwing Zygote off. Apparently Diffractor recently [changed](https://github.com/JuliaDiff/Diffractor.jl/pull/176) their behaviour to strip `boundscheck`, so perhaps we can copy that in Zygote. cc @staticfloat to confirm I have things right.

**Comment by staticfloat** [comment]
Yes, I think we need to just ignore `:boundscheck`, e.g. here: https://github.com/FluxML/Zygote.jl/blob/2f4937096ee1db4b5a67c1c31fe3ebeab1c96c8c/src/forward/compiler.jl#L51C1-L52

**Comment by staticfloat** [comment]
Oh, actually, it's on the next line down.  Hmmm.

**Comment by ToucheSir** [comment]
Oh, that doesn't apply it all because it's specific to the (now non-functional and basically vestigial) forward mode. For reverse mode we hit https://github.com/FluxML/Zygote.jl/blob/2f4937096ee1db4b5a67c1c31fe3ebeab1c96c8c/src/compiler/reverse.jl#L314. The list in https://github.com/FluxML/Zygote.jl/blob/2f4937096ee1db4b5a67c1c31fe3ebeab1c96c8c/src/compiler/reverse.jl#L281 may need auditing as well.

**Comment by staticfloat** [comment]
Yes, I think you found it, we should likely be adding `:boundscheck` into that list.

**Comment by ToucheSir** [comment]
The fix shouldn't be too bad (replace any occurrence of `Expr(:boundscheck)` with `true` in the IR), but should come with a test. Can anyone cook up a simple one, or better yet a complete PR?

**Comment by cortner** [comment]
I can convert my example into a short test but I doubt it is representative. I'm afraid I wasn't able to follow the discussion and don't understand the issue yet.

**Comment by ToucheSir** [comment]
We just need a simple function which when lowered contains an `Expr(:boundscheck)` somewhere in its IR. The test would be seeing if the boundscheck is still active (e.g. triggering an OOB access and catching it) when the function is differentiated.

**Comment by staticfloat** [comment]
You can use this for inspiration: https://github.com/JuliaDiff/Diffractor.jl/pull/177/files

**Comment by cortner** [comment]
IR = [intermediate representation](https://docs.julialang.org/en/v1/devdocs/ssair/) ??
OOB = out of bounds ??

**Comment by cortner** [comment]
> We just need a simple function which when lowered contains an `Expr(:boundscheck)` somewhere in its IR. The test would be seeing if the boundscheck is still active (e.g. triggering an OOB access and catching it) when the function is differentiated.

Ok, this seems straightforward. Zygote already catches this correctly. This passes on `master`: 
```julia 
using Zygote, Test 

function foo(x)
   t = (x, x)
   return t[1] + 1
end

@test Zygote.gradient(foo, 1.0)[1] == 1.0

# Test that `@inbounds` is ignored by Diffractor
function foo_errors(x)
   t = (x, x)
   @inbounds return t[3] + 1
end

@test_throws BoundsError Zygote.gradient(foo_errors, 1.0)
```

And I don't understand how it is related to my original problem since it triggers a different exception.

**Comment by cortner** [comment]
On the other hand, adding `:boundscheck` to the list in 

https://github.com/FluxML/Zygote.jl/blob/2f4937096ee1db4b5a67c1c31fe3ebeab1c96c8c/src/compiler/reverse.jl#L281

does fix my problem. Thank you for that suggestion.

**Comment by ToucheSir** [comment]
That does fix the issue at hand, but my problem with it is that the list there is telling Zygote what to _allow_ in the final generated function. Whereas Diffractor explicitly excludes it because of safety concerns. Hence we need some mechanism other than the passthrough check, but as you note that requires a test function which contains some of the aforementioned `Expr`s in the first place.

**Comment by cortner** [comment]
Ok, the function `grad_f` below triggers the error in the op: 
```julia
f(x, ps::NamedTuple) = model(x, ps.W) 
grad_f(x, ps) = Zygote.gradient( _x -> model(_x, ps), x )[1]
``` 
So presumably it will contain that `:boundscheck`  ??

Sorry if I'm being slow, I'm a perfectly competent scientific programmer, but this goes much deeper than what I normally think about.

**Comment by cortner** [comment]
@tjjarvinen I think you are better equipped than I to make this PR? Would you mind taking a look? It would be very useful for us to have this fix in `Zygote.jl`.

**Comment by cortner** [comment]
For the record here is a minimal test that seems to confirm the change suggested by ToucheSir appears to fix the (first) problem: 
```julia
using LinearAlgebra: dot 
f(x, ps::NamedTuple) = model(x, ps.W) 
grad_f(x, ps) = Zygote.gradient( _x -> model(_x, ps), x )[1]
let x0 = randn(5), a0 = randn(5) 
   g(ps) = dot(a0, grad_f(x0, ps))
   ps0 = ( W = randn(5), )
   @test Zygote.gradient(g, ps0)[1] == (W = a0,)
end
```
