### ISSUE TITLE
Failing to precompile Flux and Zygote

### ISSUE THREAD

**Issue by yuvalwas** [FluxML/Zygote.jl#1456]
Hello, I failed to precompile Zygore on my Institute's HPC. Would appreciate any help.

# Stacktrace
Precompiling project...
[91m  ✗ [39m[90mZygote[39m
[91m  ✗ [39mFlux
  0 dependencies successfully precompiled in 112 seconds (337 already precompiled)

ERROR: LoadError: The following 1 direct dependency failed to precompile:

Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]

Failed to precompile Flux [587475ba-b771-5e3f-ad9e-33799f191a9c] to /home/labs/tsodyks/yuvalw/.julia/compiled/v1.7/Flux/jl_6Q1dTi.
ERROR: LoadError: MethodError: no method matching iterate(::Core.CodeInfo)
Closest candidates are:
  iterate(!Matched::Union{LinRange, StepRangeLen}) at /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/base/range.jl:826
  iterate(!Matched::Union{LinRange, StepRangeLen}, !Matched::Integer) at /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/base/range.jl:826
  iterate(!Matched::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/base/dict.jl:695
  ...
Stacktrace:
  [1] indexed_iterate(I::Core.CodeInfo, i::Int64)
    @ Base ./tuple.jl:92
  [2] pullback(::Function, ::Zygote.Context{false}, ::Int64, ::Vararg{Int64})
    @ Zygote ~/.julia/packages/Zygote/4SSHS/src/compiler/interface.jl:44
  [3] pullback(::Function, ::Int64, ::Int64)
    @ Zygote ~/.julia/packages/Zygote/4SSHS/src/compiler/interface.jl:42
  [4] gradient(::Function, ::Int64, ::Vararg{Int64})
    @ Zygote ~/.julia/packages/Zygote/4SSHS/src/compiler/interface.jl:96
  [5] top-level scope
    @ ~/.julia/packages/Zygote/4SSHS/src/precompile.jl:17
  [6] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
  [7] include
    @ ~/.julia/packages/Zygote/4SSHS/src/Zygote.jl:1 [inlined]
  [8] macro expansion
    @ ~/.julia/packages/Requires/Z8rfN/src/Requires.jl:40 [inlined]
  [9] precompile()
    @ Zygote ~/.julia/packages/Zygote/4SSHS/src/Zygote.jl:63
 [10] macro expansion
    @ ~/.julia/packages/PrecompileTools/kmH5L/src/workloads.jl:85 [inlined]
 [11] top-level scope
    @ ~/.julia/packages/Zygote/4SSHS/src/Zygote.jl:84
 [12] include
    @ ./Base.jl:418 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1318
 [14] top-level scope
    @ none:1
 [15] eval
    @ ./boot.jl:373 [inlined]
 [16] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [17] top-level scope
    @ none:1
in expression starting at /home/labs/tsodyks/yuvalw/.julia/packages/Zygote/4SSHS/src/precompile.jl:17
in expression starting at /home/labs/tsodyks/yuvalw/.julia/packages/Zygote/4SSHS/src/Zygote.jl:1
ERROR: LoadError: Failed to precompile Zygote [e88e6eb3-aa80-5325-afca-941959d7151f] to /home/labs/tsodyks/yuvalw/.julia/compiled/v1.7/Zygote/jl_vTqQFV.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base ./loading.jl:1466
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1410
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1120
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
  [7] include
    @ ./Base.jl:418 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1318
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:373 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [12] top-level scope
    @ none:1
in expression starting at /home/labs/tsodyks/yuvalw/.julia/packages/Flux/n3cOc/src/Flux.jl:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/Types.jl:68
 [2] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:1362
 [3] precompile
   @ /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:1013 [inlined]
 [4] #precompile#220
   @ /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:1011 [inlined]
 [5] precompile()
   @ Pkg.API /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/share/julia/stdlib/v1.7/Pkg/src/API.jl:1011
 [6] top-level scope
   @ ~/clusterless/wexac_utils/env_setup.jl:10
in expression starting at /home/labs/tsodyks/yuvalw/clusterless/wexac_utils/env_setup.jl:5
```

# Julia version
```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 5320 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, icelake-server)
Environment:
  EBVERSIONJULIA = 1.7.1
  EBROOTJULIA = /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64
  EBDEVELJULIA = /apps/easybd/easybuild/software/Julia/1.7.1-linux-x86_64/easybuild/Julia-1.7.1-linux-x86_64-easybuild-devel
```

# Zygote and Flux versions
Zygote v0.6.64
Flux v0.13.17

**Comment by yuvalwas** [comment]
I see that this is similar to #1449. Do you think working with the latest Julia version would solve this?

**Comment by ToucheSir** [comment]
That would be ideal. It's possible some 1.7 and/or 1.8 versions may have received the same backport fix that was mentioned in #1449, but 1.7.1 likely wouldn't have because of how old it is.

**Comment by voroskoi** [comment]
Hi,

I have the same issue with julia-1.9.3.
If I try to precompile just Zygote that also fails without any error message, it just shows a red X.

I am new to julia, is there a verbose flag or something I can switch on to get a helpful error message?

**Comment by ToucheSir** [comment]
That sounds more like https://github.com/FluxML/Zygote.jl/issues/1455 since you're using a recent version of Julia. I'd try the steps in https://github.com/FluxML/Zygote.jl/issues/1455#issuecomment-1720448912 and open a new thread if they don't work.

**Comment by voroskoi** [comment]
I have opened #1457 after trying to build in a clean environment.

**Comment by yuvalwas** [comment]
Updating to 1.9.3. more or less worked for me. (Some other packages then failed 😞 )
