### ISSUE TITLE
#mutate: push!() fails to differentiate

### ISSUE THREAD

**Issue by NiklasGustafsson** [FluxML/Zygote.jl#147]
The following code raises an exception when using the #mutate branch:

```
using Pkg; Pkg.activate(".");
pkg"add Zygote#mutate"

using Zygote

function f(w::Array{Float64,2}, x::Array{Float64,2})

    result = []

    for i = 1:size(x,2)
        h = w[:,i] .+ x[:,i]
        push!(result, h)
    end

    cat = hcat(result...)
    return sum(cat)
end

s = rand(5,100)
x = rand(5,100)

v = f(s,x)

l = Zygote.gradient((w)-> f(w, x), s)
```

**Comment by MikeInnes** [comment]
Now working on the latest commit.

**Comment by overshiki** [comment]
Hi
I just tested the above piece of code in Zygote v0.6.40, it does not work. Is differentiation of `push!` currently a support feature?

**Comment by ToucheSir** [comment]
It is not. Note the use of an experimental branch above. If you must have a mutable vector, `Buffer` or hiding the mutation behind a `rrule` are the only options.

**Comment by overshiki** [comment]
Hi @ToucheSir 
I see. 
Cool, thanks!
