### ISSUE TITLE
`sort(x; rev=true)` is not supported

### ISSUE THREAD

**Issue by lkdvos** [FluxML/Zygote.jl#1492]
Currently there is no support for `sort(::AbstractVector; rev::Bool)`. This is similar to what happened in #586, and would just need to add the keyword to the `@adjoint` definition. Alternatively, it is possible to just remove the definition and rely on the one that is defined by `ChainRules`, which automatically handles both options. I can open up a PR for this, if someone could let me know which solution is preferred.

```julia-repl
julia> using Zygote
julia> jacobian(x -> sort(x), [1,2,3])
([1 0 0; 0 1 0; 0 0 1],)
julia> jacobian(x -> sort(x; rev=true), [1,2,3])
ERROR: MethodError: no method matching adjoint(::Zygote.Context{false}, ::typeof(sort), ::Vector{Int64}; rev::Bool)
```

**Comment by mcabbott** [comment]
Generally we should delete `@adjoint` rules & move things to ChainRules. This one doesn't look like it does anything very fancy, probably safe to delete (but keep the tests) which is an easy PR.

https://github.com/FluxML/Zygote.jl/blob/c1d82be3a32ff505439273f708a238608bbd45be/src/lib/array.jl#L254-L257

Probably the same is true of the rule for `filter` just below.
