### ISSUE TITLE
OOM when computing the gradient in an embarrassingly parallel problem

### ISSUE THREAD

**Issue by turquoisedragon2926** [FluxML/Zygote.jl#1504]
Hello,

Not sure if this is the right place, but I am running into a issue where we observe that we run out of memory on embarrassingly parallel gradient computation when the memory per task / problem_size is constant.

More details are here: [Julia Forum](https://discourse.julialang.org/t/mpi-jl-zygote-oom-on-embarrassingly-parallel-tasks/110622)

Thank you for any help

**Comment by ToucheSir** [comment]
After reading through and commenting on the Discourse thread, I'm going to close this as the issue does not appear to be related to Zygote. In general, I'd only recommend cross-posting from Discourse when you don't get responses after multiple days. In this case, it looks like members of the community are being more than responsive enough.
