### ISSUE TITLE
Support try/catch by assuming try branch 

### ISSUE THREAD

**Issue by paulxshen** [FluxML/Zygote.jl#1516]
### Motivation and description

Lots of packages still use try/catch. Normal execution uses try, so we can easily support it by always assuming try branch? Maybe raise a warning of this assumption.

**Comment by ToucheSir** [comment]
Not sure I understand the request, but I think this is covered by https://github.com/FluxML/Zygote.jl/pull/1474.

**Comment by paulxshen** [comment]
Great! Can you update the docs https://fluxml.ai/Zygote.jl/stable/limitations/ ? Also I still see try/catch errors - even when nothing is thrown - will look more into..

**Comment by ToucheSir** [comment]
That PR isn't merged. I don't see why the docs would be updated?

**Comment by paulxshen** [comment]
Sorry thought it was merged

**Comment by Pangoraw** [comment]
it should now work in zygote@0.6.71
