### ISSUE TITLE
Incorrect `nothing` gradient

### ISSUE THREAD

**Issue by juliohm** [FluxML/Zygote.jl#1538]
MWE:

```julia
julia> using Zygote

julia> f(x, y) = y
f (generic function with 1 method)

julia> gradient(f, 0, 0)
(nothing, 1.0)
```

On a fresh environment with the latest stable release of Zygote.jl

**Comment by CarloLucibello** [comment]
Zygote can return nothing in place of zero, this is expected

**Comment by juliohm** [comment]
Thank you @CarloLucibello for clarifying this. Shouldn't this `nothing` value be handled for end-users though with multiple dispatch? It becomes difficult to write generic math when `nothing` is returned sometimes.

As people suggested on Zulip, one could define:

```
denothing(x) = x
denothing(::Nothing) = 0.0
```

to automatically return `0.0` in all cases?

**Comment by CarloLucibello** [comment]
Nothing can be returned in correspondence of variables of any type (numbers, arrays, custom types) so take that into account.

**Comment by juliohm** [comment]
Should there be a special `Zero` singleton type that behaves like zero every time? Why can't we rely on `zero(T)` for example?
