### ISSUE TITLE
Params()-based gradient with respect to scalars fails silently

### ISSUE THREAD

**Issue by rhaps0dy** [FluxML/Zygote.jl#159]
The following code will return `nothing`, which is incorrect.
```julia
a = 1.0;
g = gradient(Params([a])) do
    a
end;
g[a]
```
But this code correctly returns `[1.0]`.

```julia
a = [1.0];
g = gradient(Params([a])) do
    a[1]
end;
g[a]
```

@willtebbutt  found that this is probably because `a` is not allocated in the heap, so maybe it's not easy or possible to detect by Zygote? Could it be possible to warn the user or return the correct answer?

**Comment by MikeInnes** [comment]
Yup, should definitely be an error. Thanks for the report.
