### ISSUE TITLE
Some simple optimisations

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Zygote.jl#16]
Following on from #2; I should really be paper-writing, but we're dangerously close to matching the hand-written gradient for `logsumexp`, so here we are. Poking at it I found a few general optimisations that will help close the gap.

The most egregious issue is that ForwardDiff's method for `exp` actually calculates `exp(x)` twice, presumably due to a failure of CSE. But that's easy to fix and will shave off a bunch of time.

The hand-written version takes advantage of the fact that the gradient of `A` (`1 - sema/sema`) cancels out. I don't think we can elide this completely -- we're honour-bound to evaluate the chain rule everywhere -- but through optimisations to `maximum` and `broadcast` we can at least avoid any extra allocations for it; then the scalar ops should be inconsequential.

On broadcast, it occurred to me that we can and may want to do optimisations on the `broadcasted` struct before evaluating. The most obvious thing is to pick up on cases like this, where we don't need to actually use dual numbers but can just use a function of the output. Not sure if that would win over a properly-optimised dual number implementation, but it's worth exploring.

It'd also be good to avoid explicitly instantiating the gradient of `sum`, instead using broadcasting to expand it. We can get the same effect with a `FillArray`.

**Comment by jrevels** [comment]
> The most egregious issue is that ForwardDiff's method for exp actually calculates exp(x) twice

Oof, can you open an issue in ForwardDiff for this? That's definitely a perf bug. We should add that to our tests...

**Comment by jrevels** [comment]
> Not sure if that would win over a properly-optimised dual number implementation, but it's worth exploring.

idk where the code for this kernel is, but if your broadcast kernel is sufficiently static and has higher input arity than output arity, than you should be able to beat ForwardDiff there. It's when the kernel is dynamic that forward-mode shines. 

Note, though, that if the input/output arity ratio is close enough to 1 (e.g. ~3) than LLVM might optimize the ForwardDiff calculation enough that it basically becomes the same as the reverse-mode computation. Usually it's a combination of scalar-level vectorization and reduction via sparsity (e.g. LLVM figures out that something is `0` and thus not worth computing) that achieves this.

**Comment by MikeInnes** [comment]
I can do you one better than an issue -- https://github.com/JuliaDiff/ForwardDiff.jl/pull/357

**Comment by MikeInnes** [comment]
The approach for `g1` should be fine, but you might find that Julia boxes the closure reference. Should be fixable if you use a `let` block.

**Comment by MikeInnes** [comment]
Most of these are done now:
```julia
julia> @btime logsumexp(x)
  954.130 ns (1 allocation: 896 bytes)
5.141724249721802

julia> @btime derivative(logsumexp, x)
  1.262 μs (21 allocations: 2.19 KiB)
```
Still more allocations than I'd like, but hopefully we can keep fixing those as we go along.
