### ISSUE TITLE
Wrong result when computing complex derivative of `sum(1im*x)`

### ISSUE THREAD

**Issue by PhilipVinc** [FluxML/Zygote.jl#160]
The two functions below are mathematically equivalent, but the gradient computed by `Zygote` is different. The correct gradient is that of `g2`.

```
using Zygote
g(W::AbstractArray{T}) where T = sum(W* T(1)im)
g2(W::AbstractArray{T}) where T = sum(W)*T(1)im

W=[1.0+0.5im, 0.5+0.5im]

# Wrong
y, back = forward(g, W)
der1  = conj(back(Int8(1))[1])

# Correct
y, back = forward(g2, W)
der2  = conj(back(Int8(1))[1])
```

where you'll find
```
> der1
2-element Array{Complex{Float64},1}:
 0.0 - 1.0im
 0.0 - 1.0im

> der2
2-element Array{Complex{Float64},1}:
 0.0 + 1.0im
 0.0 + 1.0im
```

**Comment by GiggleLiu** [comment]
Confirmed a bug, we should probably make a list of tested complex valued functions. Otherwise hard to debug.

**Comment by MikeInnes** [comment]
Most likely fixed by https://github.com/FluxML/Zygote.jl/pull/156. That should be the last thing we have to fix for correct complex AD.

**Comment by MikeInnes** [comment]
Now fixed on master.
