### ISSUE TITLE
ERROR: Non-differentiable function fptrunc with higher-order gradients of custom adjoint

### ISSUE THREAD

**Issue by jessebett** [FluxML/Zygote.jl#161]
Some background is that I am trying to write a wrapper for `z` so that the forward evaluation returns `z`, so the gradient `dz/dz = I` but the gradient wrt another value `t` is given by a differentiable function `dz/dt = f(z,t)`.

```
z_(f,z,t) = z
@adjoint z_(f,z,t) = z, Δ -> (nothing,Δ,Δ * f(z,t))
```

And taking first order gradients with this works as anticipated:

```
f(z,t) = z.*t.^3
z_(f,1.,2.) #1.0
gradient(z->z_(f,z,2.),1.) #(1,)
gradient(x->z_(f,1.,x),2.) #(8.0,)
```

However, taking a higher-order gradient fails with `ERROR: Non-differentiable function fptrunc`
```
gradient(t->gradient(x->z_(f,1.,x),t)[1][1],2.)
```

This also happens when I'm trying to take the higher order gradient of the intended use, when `f` is a neural network:

```
nn = Flux.mapleaves(Tracker.data,Chain(Dense(2,4,tanh),Dense(4,1)))
g(z,t) = nn([z,t]) 
z_(g,1.,2.)
gradient(z->z_(g,z,2.),1.)
gradient(x->z_(g,1.,x),2.)
gradient(t->gradient(x->z_(g,1.,x),t)[1][1],2.)
```

**Comment by jessebett** [comment]
Correction, that first `f(z,t)` does work... It was a problem where I forgot to `Zygote.refresh()` after that neural network example was run (they shared the same function name at some point). So this bug occurs because of the nn example.

**Comment by MikeInnes** [comment]
These examples are all working for me now; I guess the `fptrunc` issue was just #167. Note that nested gradients are not that well tested, so you'll want to tread with some care here, but please do keep reporting anything that's off.
