### ISSUE TITLE
Non-differentiable function fptrunc with gradients of Flux models

### ISSUE THREAD

**Issue by jessebett** [FluxML/Zygote.jl#167]
I ran into this consistently annoying trap with Tracker:
```
nn = Dense(1,2,tanh)
Tracker.gradient(t->nn([t])[1],2.)
ERROR: MethodError: no method matching Float32(::Tracker.TrackedReal{Float64})
```

And realized that, in order for gradient to work, I'd have to wrap the input into an array:
`Tracker.gradient(t->nn(t)[1],[2.])` this works. But this should be equivalent to the first code I attempted. So that's not great.

I wanted to see if this issue will be a problem in Zygote:
```
Zygote.gradient(t->nn(t)[1],[2.])
ERROR: Non-differentiable function fptrunc

Zygote.gradient(t->nn([t])[1],2.)
ERROR: Non-differentiable function fptrunc
```

Both return that error with `fptrunc`. Currently blocking gradients through Flux models.

**Comment by jessebett** [comment]
This is the issue I ran into in #161, which I had assumed was due to the higher order composition...

**Comment by MikeInnes** [comment]
This works for me, at least on Zygote master.
