### ISSUE TITLE
MethodError: no method matching *(::Zygote.Stack{Any}, ::Int64)

### ISSUE THREAD

**Issue by omalled** [FluxML/Zygote.jl#182]
I encounter an error (`MethodError: no method matching *(::Zygote.Stack{Any}, ::Int64)`) on the `mutate` branch when running the following code.

```
function g1(p)
	n = 3
	A = LinearAlgebra.diagm(-1=>fill(-p, n - 1), 0=>fill(2p, n), 1=>fill(-p, n - 1))
	b = ones(n)
	return (A \ b)[1]
end

@show g1(1.0)
@show g1'(1.0)
```

**Comment by MikeInnes** [comment]
The method error here is (was) definitely a compiler bug, but seems to have gone away on master. We'll still need a custom adjoint for something in this; feel free to open a separate issue for that.
