### ISSUE TITLE
segfaults on problems with sparse matrices

### ISSUE THREAD

**Issue by omalled** [FluxML/Zygote.jl#183]
The code below produces a segfault:
```
import SparseArrays
import Zygote
g4(p) = (SparseArrays.sparse([1, 2], [1, 2], [p, p^2]) \ [1, 1])[1]
@show g4(1.0)
@show g4'(1.0)#segfault
```

**Comment by MikeInnes** [comment]
Same response as #182. We do need a custom adjoint make this work but the segfault is gone. If you try master (I'm about to tag a new version as well) we can work out how to get this example running.
