### ISSUE TITLE
relation between builtin FillArray and FillArrays

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Zygote.jl#190]
I'm trying to get rid of the mutation happens here

https://github.com/QuantumBFS/LuxurySparse.jl/blob/09795174112120a542fe15b786c8379e7e4b28dc/src/arraymath.jl#L29

with `Fill` (it doesn't make sense to add Zygote as deps for `FillArrays`) but I'm wondering if Zygote could use `FillArrays` directly, so there're no duplicated things.

And we could include some `adjoints` for `FillArrays` directly here since it is a dependency already.

**Comment by MikeInnes** [comment]
Closed by #191.
