### ISSUE TITLE
Crash on 0.7.0-rc3.0

### ISSUE THREAD

**Issue by awf** [FluxML/Zygote.jl#2]
Attached jl produces attached log when run with 
julia .\zg-logsumexp.jl

Apologies, haven't tested with 1.0.   Zygote pkg is added from master in this repo.

[zg.log](https://github.com/FluxML/Zygote.jl/files/2291527/zg.log)

```
using Test
using Printf
using Zygote
using BenchmarkTools

# logsumexp()
function logsumexp(x::Array{Float64,1})
  A = maximum(x);
  ema = exp.(x .- A);
  sema = sum(ema);
  log(sema) + A;
end

r = rand(5);
@test logsumexp(r) ≈ log(sum(exp.(r))) atol=1.0e-8
@printf("logsumexp: %f = %f\n", logsumexp(r), log(sum(exp.(r))));

# logsumexp()
function logsumexp_both(x::Array{Float64,1})
  A = maximum(x);
  ema = exp.(x .- A);
  sema = sum(ema);
  l = log(sema) + A;
  Jacobian = ema ./ sema;
  return (l, Jacobian)
end

x = rand(100)

"Timing logsumexp_both" |> println
@btime logsumexp_both(x)

"Timing zygote" |> println
@btime Zygote.gradient(logsumexp, x)

```

**Comment by jekbradbury** [comment]
Zygote requires Julia built from source including Mike’s patches; I have a Docker image with such a build here: `docket pull gcr.io/personal-204923/julia:zygote`

**Comment by MikeInnes** [comment]
We should ideally not be crashing Julia's codegen here, as opposed to just throwing an error, but this is probably easily fixed by adding the right gradient definition (of which we have very few right now; `*` and `+` with scalars is enough to check the chain rule is working :)). I'll take a look shortly.

**Comment by ngphuoc** [comment]
I modified the example in the README to add a loss function and it crashed with a sigfault too:
```julia

using Zygote: @grad, Params, gradient

W, b = rand(2, 3), rand(2);

predict(x) = W*x .+ b;

loss(x,y) = sum(abs2, y .- predict(x))

g = gradient(() -> sum(loss([1,2,3], [1, 1])), Params([W, b]))

g[W], g[b]

```

**Comment by MikeInnes** [comment]
I added a simple gradient def for `maximum` which fixes the original example. I really need to bring over all the definitions that Flux has.

I also just realised that our broadcast grad is not type-stable, so this benchmark comes out a bit slower than it needs to be.

**Comment by MikeInnes** [comment]
Current *release* Julia (I'll remove any need for a source build this week, though there'll still be a flag for type system abuse).

```julia
(v1.0) pkg> add Zygote#master IRTools#master

julia> using Zygote, BenchmarkTools

julia> function logsumexp(x::Array{Float64,1})
         A = maximum(x)
         ema = exp.(x .- A)
         sema = sum(ema)
         log(sema) + A
       end
logsumexp (generic function with 1 method)

julia> const x = rand(100);

julia> @btime logsumexp(x)
  1.515 μs (1 allocation: 896 bytes)
5.119135839482861

julia> @btime Zygote.gradient(logsumexp, x);
  4.882 μs (35 allocations: 7.61 KiB)
```

Almost all of the time is spent in broadcast; I imagine there's yet more that we could do to be cleverer here, though it's hard to imagine how we'd get as good as the hand written version without special knowledge.

**Comment by chriselrod** [comment]
The overhead for small problems is still pretty high (so the StaticArrays aren't fast yet), but...
```julia
julia> @btime Zygote.gradient(logsumexp, $x);
  2.832 μs (35 allocations: 7.61 KiB)

julia> @btime ReverseDiff.gradient!($results, $compiled_tape, $inputs);
  15.900 μs (0 allocations: 0 bytes)

julia> @btime ForwardDiff.gradient!($res, logsumexp, x, $cfg);
  25.158 μs (10 allocations: 87.50 KiB)
```

**Comment by MikeInnes** [comment]
Nice!

I did notice one of the earlier StaticArrays not infering properly. Feel free to open a new issue for anything like that.

**Comment by awf** [comment]
Very nice.   Note that my initial code wasn't quite comparing apples to apples: logsumexp_both computes the function value too.   For timing, we should compare Zygote.gradient to
```julia
# grad_logsumexp()
function grad_logsumexp(x::Array{Float64,1})
  A = maximum(x);
  ema = exp.(x .- A);
  sema = sum(ema);
  # l = log(sema) + A;
  Jacobian = ema ./ sema;
  return (l, Jacobian)
end
````
