### ISSUE TITLE
Wrong gradient for `x -> x / maximum([x])`

### ISSUE THREAD

**Issue by under-Peter** [FluxML/Zygote.jl#208]
Hi,
with `Zygote v0.3.1`, I'm getting
```
julia> Zygote.gradient(x -> x/maximum([x]),1.)
(1.0,)
```
where I'd expect a `0` since the output is constant equal to one.
In `Flux v0.8.3` the gradient is correct:
```
julia> Flux.Tracker.gradient(x -> x/maximum([x]), 1)
(0.0 (tracked),)
```

This is a minimal example, in reality the problem appeared because `Zygote` ignored a scaling of a matrix by its maximal entry.
```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by under-Peter** [comment]
A workaround is using `argmax`, i.e. instead of
```
x / maximum([x])
```
use 
```
x / x[argmax(x)]
```

**Comment by MikeInnes** [comment]
@avik-pal is this the same as #197?

**Comment by avik-pal** [comment]
Yes, and this seems to be a much more minimal example.
