### ISSUE TITLE
Failing simple use case

### ISSUE THREAD

**Issue by ViralBShah** [FluxML/Zygote.jl#242]
```
function s(x) 
         t = 0.0
         sign = -1.0 
         for i in 1:19   
            if isodd(i)
               newterm = x^i/factorial(i)
               abs(newterm)<1e-8 && return t
               println(i)
               sign = -sign
               t += sign * newterm
            end
         end
         return t 
       end
```

julia> Zygote.gradient(s, 1.0)
1
3
5
7
9
11
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Core.Compiler.NewNode, (4,)}[
  Core.Compiler.NewNode(pos=5, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(2), 0x01), line=0),
  Core.Compiler.NewNode(pos=41, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(40), 0x01), line=0),
  Core.Compiler.NewNode(pos=51, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(50), 0x01), line=0),
  Core.Compiler.NewNode(pos=78, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(74), 0x01), line=0)], i=(25,))
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:217
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:417
jl_bounds_error_ints at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:183
getindex at ./array.jl:729 [inlined]
getindex at ./compiler/ssair/ir.jl:727 [inlined]
abstract_eval_ssavalue at ./compiler/ssair/queries.jl:61 [inlined]
argextype at ./compiler/utilities.jl:171
argextype at ./compiler/utilities.jl:157 [inlined]
assemble_inline_todo! at ./compiler/ssair/inlining.jl:796
ssa_inlining_pass! at ./compiler/ssair/inlining.jl:59 [inlined]
run_passes at ./compiler/ssair/driver.jl:118
optimize at ./compiler/optimize.jl:164
typeinf at ./compiler/typeinfer.jl:35
typeinf_edge at ./compiler/typeinfer.jl:497
abstract_call_method at ./compiler/abstractinterpretation.jl:345
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:85
abstract_eval_call at ./compiler/abstractinterpretation.jl:803
abstract_eval at ./compiler/abstractinterpretation.jl:890
typeinf_local at ./compiler/abstractinterpretation.jl:1135
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1191
typeinf at ./compiler/typeinfer.jl:14
typeinf_ext at ./compiler/typeinfer.jl:576
typeinf_ext at ./compiler/typeinfer.jl:613
jfptr_typeinf_ext_1.clone_1 at /Users/viral/Desktop/Julia Releases/Julia-1.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2197 [inlined]
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1571 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:255
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1797
jl_fptr_trampoline at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1841
gradient at /Users/viral/.julia/packages/Zygote/VeaFW/src/compiler/interface.jl:47
unknown function (ip: 0x12885a508)
jl_fptr_trampoline at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1842
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:323
eval_stmt_value at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:362 [inlined]
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:759
jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:885
Interpreter frame (ip: 1)
Core.CodeInfo(code=Array{Any, (3,)}[
  Expr(:call, Base.getproperty, :Zygote, :(:gradient)),
  Expr(:call, SSAValue(1), :s, 1),
  Expr(:return, SSAValue(2))], codelocs=Array{Int32, (3,)}[1, 1, 1], method_for_inference_limit_heuristics=nothing, ssavaluetypes=3, linetable=Array{Any, (1,)}[Core.LineInfoNode(mod=Main, method=Symbol("top-level scope"), file=:none, line=0, inlined_at=0)], ssaflags=Array{UInt8, (0,)}[], slotflags=Array{UInt8, (0,)}[], slotnames=Array{Any, (0,)}[], inferred=false, inlineable=false, propagate_inbounds=false, pure=false)jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:764
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:773 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:793
eval at ./boot.jl:328
eval_user_input at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1571 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:572
(0.5403023037918872,)

**Comment by ViralBShah** [comment]
Also, ```gradient(eps, 1.0)``` gives no result as opposed to 0.0 which is what `ForwardDiff` does.

**Comment by MikeInnes** [comment]
This works fine on master -- we just need a new tag.

The `nothing` is just Zygote's way of saying "not differentiable".
