### ISSUE TITLE
Zygote does not go through DiffEq all the way

### ISSUE THREAD

**Issue by ViralBShah** [FluxML/Zygote.jl#243]
It would be great if this simple example can serve as a test case for differentiating all of DiffEq.

``` 
using OrdinaryDiffEq
ẍ(ẋ,x,p,t) = -x # The ODE
x₀,ẋ₀ = 0.0,1.0 # Initial Conditions
prob = SecondOrderODEProblem(ẍ,ẋ₀,x₀,(0.0,1.0))
sol = solve(prob,DPRKN6())
sol(1.0)[1]

Zygote.gradient( t->sol(t)[2], 1.0)
```
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Core.Compiler.NewNode, (3,)}[
  Core.Compiler.NewNode(pos=3, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(2), 0x01), line=0),
  Core.Compiler.NewNode(pos=53, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(52), 0x01), line=0),
  Core.Compiler.NewNode(pos=61, attach_after=false, typ=Bool, node=Expr(:call, Core.:(===), SSAValue(58), 0x01), line=0)], i=(12,))
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:217
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:417
jl_bounds_error_ints at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:183
getindex at ./array.jl:729 [inlined]
getindex at ./compiler/ssair/ir.jl:727 [inlined]
abstract_eval_ssavalue at ./compiler/ssair/queries.jl:61 [inlined]
argextype at ./compiler/utilities.jl:171
argextype at ./compiler/utilities.jl:157 [inlined]
assemble_inline_todo! at ./compiler/ssair/inlining.jl:796
ssa_inlining_pass! at ./compiler/ssair/inlining.jl:59 [inlined]
run_passes at ./compiler/ssair/driver.jl:118
optimize at ./compiler/optimize.jl:164
typeinf at ./compiler/typeinfer.jl:35
typeinf_edge at ./compiler/typeinfer.jl:497
abstract_call_method at ./compiler/abstractinterpretation.jl:345
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:85
abstract_eval_call at ./compiler/abstractinterpretation.jl:803
abstract_eval at ./compiler/abstractinterpretation.jl:890
typeinf_local at ./compiler/abstractinterpretation.jl:1135
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1191
typeinf at ./compiler/typeinfer.jl:14
typeinf_edge at ./compiler/typeinfer.jl:497
abstract_call_method at ./compiler/abstractinterpretation.jl:345
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:85
abstract_eval_call at ./compiler/abstractinterpretation.jl:803
abstract_eval at ./compiler/abstractinterpretation.jl:890
typeinf_local at ./compiler/abstractinterpretation.jl:1135
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1191
typeinf at ./compiler/typeinfer.jl:14
typeinf_ext at ./compiler/typeinfer.jl:576
typeinf_ext at ./compiler/typeinfer.jl:613
jfptr_typeinf_ext_1.clone_1 at /Users/viral/Desktop/Julia Releases/Julia-1.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2197 [inlined]
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1571 [inlined]
jl_type_infer at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:255
jl_compile_method_internal at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1797
jl_fptr_trampoline at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1841
gradient at /Users/viral/.julia/packages/Zygote/VeaFW/src/compiler/interface.jl:47
unknown function (ip: 0x12885a508)
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:323
eval_stmt_value at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:362 [inlined]
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:759
jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:885
Interpreter frame (ip: 8)
Core.CodeInfo(code=Array{Any, (10,)}[
  Expr(:thunk, Core.CodeInfo(code=Array{Any, (4,)}[
  Expr(:global, Symbol("##17#18")),
  Expr(:const, Symbol("##17#18")),
  Expr(:struct_type, Symbol("##17#18"), Expr(:call, Core.svec), Expr(:call, Core.svec), Core.Function, Expr(:call, Core.svec), false, 0),
  Expr(:return, nothing)], codelocs=Array{Int32, (4,)}[1, 1, 1, 1], method_for_inference_limit_heuristics=nothing, ssavaluetypes=4, linetable=Array{Any, (1,)}[Core.LineInfoNode(mod=Main, method=Symbol("top-level scope"), file=:none, line=0, inlined_at=0)], ssaflags=Array{UInt8, (0,)}[], slotflags=Array{UInt8, (0,)}[], slotnames=Array{Any, (0,)}[], inferred=false, inlineable=false, propagate_inbounds=false, pure=false)),
  Expr(:call, Core.svec, Symbol("##17#18"), Core.Any),
  Expr(:call, Core.svec),
  Expr(:call, Core.svec, SSAValue(2), SSAValue(3)),
  Expr(:method, false, SSAValue(4), Core.CodeInfo(code=Array{Any, (3,)}[
  Expr(:call, Main.sol, Core.SlotNumber(id=2)),
  Expr(:call, Base.getindex, SSAValue(1), 2),
  Expr(:return, SSAValue(2))], codelocs=Array{Int32, (3,)}[1, 1, 1], method_for_inference_limit_heuristics=nothing, ssavaluetypes=3, linetable=Array{Any, (1,)}[Core.LineInfoNode(mod=Main, method=Symbol("#17"), file=Symbol("REPL[25]"), line=1, inlined_at=0)], ssaflags=Array{UInt8, (0,)}[], slotflags=Array{UInt8, (2,)}[0x00, 0x00], slotnames=Array{Any, (2,)}[
  Symbol("#self#"),
  :t], inferred=false, inlineable=false, propagate_inbounds=false, pure=false)),
  Expr(:call, Base.getproperty, :Zygote, :(:gradient)),
  Core.SlotNumber(id=1) = Expr(:new, Symbol("##17#18")),
  Core.SlotNumber(id=1),
  Expr(:call, SSAValue(6), SSAValue(8), 1),
  Expr(:return, SSAValue(9))], codelocs=Array{Int32, (10,)}[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], method_for_inference_limit_heuristics=nothing, ssavaluetypes=10, linetable=Array{Any, (1,)}[Core.LineInfoNode(mod=Main, method=Symbol("top-level scope"), file=:none, line=0, inlined_at=0)], ssaflags=Array{UInt8, (0,)}[], slotflags=Array{UInt8, (1,)}[0x10], slotnames=Array{Any, (1,)}[Symbol("#17")], inferred=false, inlineable=false, propagate_inbounds=false, pure=false)jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:764
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:773 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:793
eval at ./boot.jl:328
eval_user_input at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1571 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:572
(nothing,)

**Comment by MikeInnes** [comment]
Just needed master + a new adjoint.

**Comment by ViralBShah** [comment]
@chrisrackauckas
