### ISSUE TITLE
Adjoint of literal_pow fails when grad is calculated on negative input

### ISSUE THREAD

**Issue by thebhatman** [FluxML/Zygote.jl#247]
This error arises due to the fact that `literal_pow` is defined as multiplication for powers : 1, 2, 3 but for higher powers it follows this definition https://github.com/JuliaLang/julia/blob/cef655a68a4e824cbe7cca582256d61aa72eb725/base/intfuncs.jl#L253. Due to which it is trying to calculate gradient with respect to base, as well as gradient with respect to exponent. In the latter case, since the gradient involves log, it fails for negative input.

**Comment by thebhatman** [comment]
One example of failing case : 
```
using Zygote
f(x) = x .^ 10
fwd, back = Zygote.forward(f, Float32(-2))
back(one(Float32))
```
Throws domain error on all Float types, as it is trying to calculate derivative wrt to exponent.

**Comment by thebhatman** [comment]
With the change done in this PR https://github.com/JuliaDiff/DiffRules.jl/pull/36, it fixes this issue.

**Comment by MikeInnes** [comment]
Regardless of the ForwardDiff PR, we could just fix this ourselves, and I think that's worth a go.

NaN is a good option but might also cause problems in valid use cases (e.g. intentional complex differentiation). So perhaps we should just return the complex gradient if the exponent is negative.

cc @dhairyagandhi96

**Comment by dhairyagandhi96** [comment]
I think the complex gradient sounds like the correct way here, with a possible warning if we don't detect any complex typed arguments. Although I think the error would propagate either way
