### ISSUE TITLE
Mixing ForwardDiff and Zygote

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Zygote.jl#250]
```julia
gradient(x -> Dual(x, 1), 2)
```

errors, or for a slightly larger MWE:

```julia
using Zygote, ForwardDiff

function _autoback_hesvec(f,x,v)
    g = (x) -> first(Zygote.gradient(f,x))
    ForwardDiff.partials.(g(ForwardDiff.Dual{Nothing}.(x, v)), 1)
end

x = rand(300)
v = rand(300)
f(u) = sum(abs2,u)
_autoback_hesvec(f, x, v) # fails
```

This is blocking for all but the simplest uses of DiffEq with Zygote, so https://github.com/FluxML/Zygote.jl/issues/243 was closed prematurely since it was testing only a simple method.

XRef some issues caused by this: 
https://github.com/FluxML/Zygote.jl/issues/241
https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/51
https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/46
https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/31
https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/34

**Comment by MikeInnes** [comment]
Is this issue about making forward-over-reverse work, or is it about making Zygote+Diffeq work? We already have #37 for the latter, and #243 was unrelated to either.

**Comment by ChrisRackauckas** [comment]
It's about making Zygote+ForwardDiff work, which just happens to be key to fixing all of those issues.

**Comment by MikeInnes** [comment]
Your test case works fine for me:

```julia
julia> _autoback_hesvec(f, x, v) # fails
300-element Array{Float64,1}:
 1.8246600901899508
 0.03611985921591465
 1.8087073736206434
```

**Comment by MikeInnes** [comment]
In fact, forward-over-reverse seems to work ok generally (we use it for Hessians after all).

"Zygote+ForwardDiff" is pretty vague and I can't see the common thread in the issues you linked. Many of them appear to be to do with Tracker, which is a different AD. Closing this for now but feel free to reopen if you can narrow down the issue a bit.

**Comment by ChrisRackauckas** [comment]
>Many of them appear to be to do with Tracker, which is a different AD. 

Yes, but when trying the DiffEqSensitivity PR to make use of Zygote adjoints it's still not fixed yet.
