### ISSUE TITLE
gradient not working with div

### ISSUE THREAD

**Issue by thebhatman** [FluxML/Zygote.jl#258]
Here's a simple example : 
```
using Zygote
f(x, y) = div(x, y)
g = Zygote.gradient(()->f(x, y))
```
as well as this 
```
using Zygote
f(x, y) = div(x, y)
fwd, back = Zygote.forward(f, 10, 4)
back(1)
```
Both these examples give the error : `Non-differentiable function checked_sdiv_int`.

**Comment by baggepinnen** [comment]
What do you expect the derivative of integer division to be?

**Comment by thebhatman** [comment]
Yeah, I was thinking it should return `nothing` .

**Comment by thebhatman** [comment]
For example if I do this instead :
```
using Zygote
f(x, y) = trunc(Int, x/y)
x = 10
y = 4
fwd, back = Zygote.forward(f, x, y)
back(1)
```
This returns `(nothing, nothing)`, which is what I expected.

**Comment by MikeInnes** [comment]
You can probably fix this pretty easily by adding an `@nograd div` inside `lib/number.jl`.
