### ISSUE TITLE
does Zygote support functions with variant input sizes?

### ISSUE THREAD

**Issue by shi-yan** [FluxML/Zygote.jl#274]
does Zygote support functions with variant input sizes? such as an array?

also, I read the paper, it uses the ForwardDiff package, which seems to get a similar gradient as did by Zygote. What's the difference between ForwardDiff and Zygote? Sorry, I know very little about AD and julia.

**Comment by baggepinnen** [comment]
You can read about the differences here
https://github.com/MikeInnes/diff-zoo

**Comment by DilumAluthge** [comment]
> does Zygote support functions with variant input sizes? such as an array?

Here's an example of finding the gradients of arrays `W` and `b`. Is this what you mean?

```julia
julia> W, b = rand(2, 3), rand(2);

julia> predict(x) = W*x .+ b;

julia> g = gradient(Params([W, b])) do
         sum(predict([1,2,3]))
       end
Grads(...)

julia> g[W], g[b]
([1.0 2.0 3.0; 1.0 2.0 3.0], [1.0, 1.0])
```

**Comment by shi-yan** [comment]
Thanks. I tried a simple example. it does work. but I was thinking if the size of the array can be treated as a variable. And if we could get a derivative of the function with respect to the size.

Consider, for example, we want to automatically find a solution to a job. the solution to the job is an array of a series of steps. If we want to use AD to find the solution, we don't know what the final size of the solution is. We have to provide very long array as the input. If the array size can have a gradient, we could find the ideal solution size automatically. But I think it's not possible to get a gradient for that.
