### ISSUE TITLE
Double derivatives breaking the compiler 

### ISSUE THREAD

**Issue by mbeltagy** [FluxML/Zygote.jl#278]
Working today in the hackathon with @metanoid we discovered that we can send `Julia` in an apparent infinite loop when we do the following 
```julia
using Zygote
f(x) = 3* x ^ 2 + 2x + 1
df(x) = gradient(x -> f(x) |> sum, x)
ddf(x) = gradient(x -> df(x) |> sum, x)
ddf(5.)
```

This would go on forever at on `Julia 1.1.0` ... (we tried it on Windows and Linux). When tested on `Julia 1.3.0 alpha` it worked fine. 

We got it to work on `Julia 1.1.0`... with following reduction 
```julia
f(x) = 3x^2 + 2x + 1
df(x) = gradient(f, x)[1]
ddf(x) = gradient(df, x)
df(5.)
```

Curiously, if we tried `df(5)` on the above, we get a type error. 

Thank to @dhairyagandhi96 for exploring this with us and explaining some of `Flux`'s internals.

**Comment by mbeltagy** [comment]
On `1.3.0 alpha` the last snippet works for the integer input `df(5)`

**Comment by mbeltagy** [comment]
@dhairyagandhi96 found that is fixed by commit JuliaLang/julia@b2b35e9 which is currently in the 1.3.0 alpha release. However for `v1.1.0` and the soon to be released `v1.2.0` this will not work.

**Comment by dhairyagandhi96** [comment]
I think it works for 1.2 rc2 also, but do correct me if I'm mistaken

**Comment by mbeltagy** [comment]
You are absolutely right. Works for 1.2 rc2. I double checked. I guess we can close this now.
