### ISSUE TITLE
sum fails to capture closure variables

### ISSUE THREAD

**Issue by unrealwill** [FluxML/Zygote.jl#314]
There is a bug in the adjoint of sum seems to ignore the context which makes it return nothing for the gradient of captured variables.

```
using Zygote

innerOk(cap,tab) = sum( map(v->v*cap,tab ))

innerNotOk(cap,tab) = sum( v-> v*cap , tab)

function main( )

val = 3.0
tab = fill(1.0,10)
gOk = gradient( innerOk,val,tab)
println("Ok gradient :")
println(gOk)

gNotOk = gradient( innerNotOk,val,tab)
println("Bad gradient : ")
println(gNotOk)

end

main()
```
> Ok gradient :
> (10.0, [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])
> Bad gradient : 
> (nothing, [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

**Comment by MikeInnes** [comment]
On this line we assume `f` has no gradient:

https://github.com/FluxML/Zygote.jl/blob/d74f3cf5ed3c185969ff7787ee36d15c105e6653/src/lib/array.jl#L153

Should be pretty easy to fix.

**Comment by unrealwill** [comment]
I'm not sure it's easy to fix.

I replaced the whole  
`function _forward(cx::AContext, ::typeof(sum), f, xs::AbstractArray)`

with an adapted version of the map adjoint that respect the traditional type signature of sum ( except for not yet implemented dims parameter)
 
```
function ∇sum(cx, f, xs)
  ys_and_backs = map( xs -> _forward(cx, f, xs), xs)
  if isempty(ys_and_backs)
    ys_and_backs, _ -> nothing
  else
    ys, backs = unzip(ys_and_backs)
    sum(ys), function (Δ)
      Δf_and_args_zipped = map( f -> f(Δ), backs)
      Δf_and_args = unzip(Δf_and_args_zipped)
      println( "Array to reduce")
      println(  Δf_and_args[1] )
      Δf = reduce(accum, Δf_and_args[1])
      (Δf, Δf_and_args[2])
    end
  end
end

@adjoint function sum(f, xs::Union{AbstractArray,Tuple})
  ∇sum(__context__, f, xs)
end
```

Which runs fine for the simple case. 

> Ok gradient :
> (10.0, [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])
> Bad gradient : 
> Array to reduce
> NamedTuple{(:cap,),Tuple{Float64}}[(cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,), (cap = 1.0,)]
> (10.0, [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0])

However for the following more ambitious code, I have 3 main complaints : 
- Extra materialization of memory : my version is not more efficient than sum( map( f,x) ), not quite sure if it's possible to do better without calling f two times instead of one.
- Quadratic behaviour (because the adjoint of getindex is not a sparse structure, and even if it is I'm not sure julia compiler can write a non-quadratic reduce(accum) with immutable structures)
- It is hopelessly type unstable : I think the root cause is a wrong choice of convention in Zygote : if arr is of type array{T,1}, the type of its gradient should be array{ NullableTypeOf(T),1 }  where NullableTypeOf is user-specified, for example Float64-> Union{Nothing,Float64} or Float64->Float64 where nothing are transparently replaced by zeros.

```
ff( tab ) = sum( i-> i > 5 ? tab[i][2] : tab[i][1] , 1:length(tab) )

function main2()
nb = 10
tab = map(i->( convert(Float64,i), convert(Float64,i) ),1:nb)

g = gradient( ff, tab )
println( g )

end
```

> Array to reduce
> NamedTuple{(:tab,),Tuple{Array{Any,1}}}[(tab = [(1.0, nothing), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing],), (tab = [nothing, (1.0, nothing), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing],), (tab = [nothing, nothing, (1.0, nothing), nothing, nothing, nothing, nothing, nothing, nothing, nothing],), (tab = [nothing, nothing, nothing, (1.0, nothing), nothing, nothing, nothing, nothing, nothing, nothing],), (tab = [nothing, nothing, nothing, nothing, (1.0, nothing), nothing, nothing, nothing, nothing, nothing],), (tab = [nothing, nothing, nothing, nothing, nothing, (nothing, 1.0), nothing, nothing, nothing, nothing],), (tab = [nothing, nothing, nothing, nothing, nothing, nothing, (nothing, 1.0), nothing, nothing, nothing],), (tab = [nothing, nothing, nothing, nothing, nothing, nothing, nothing, (nothing, 1.0), nothing, nothing],), (tab = [nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, (nothing, 1.0), nothing],), (tab = [nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, (nothing, 1.0)],)]
> 
> (Tuple{Any,Any}[(1.0, nothing), (1.0, nothing), (1.0, nothing), (1.0, nothing), (1.0, nothing), (nothing, 1.0), (nothing, 1.0), (nothing, 1.0), (nothing, 1.0), (nothing, 1.0)],)
> 
> 
>

**Comment by MikeInnes** [comment]
I was imagining just changing that line to

```julia
y, back = forward(cx, ((f, xs) -> sum(f.(xs))), f, xs) 
```
then `back` will return the gradient of both `f` and `xs`, rather than just `xs` alone.

**Comment by unrealwill** [comment]
Yep you are right. (with an additional removing of the extra nothing on the next line)
And it works. (We should probably do the same for other reducer like prod...)
```
function _forward(cx::AContext, ::typeof(sum), f, xs::AbstractArray)
  y, back = forward(cx, ((f, xs) -> sum(f.(xs))), f, xs)
  y, ȳ -> (nothing, back(ȳ)...)
end
```

It was the opportunity for me to dig deeper about the inner workings of map, and my other points still stands.

**Comment by unrealwill** [comment]
The solution of how sum/map adjoint should be **ideally** written hit me last night :) 

```
@adjoint function sum(f, xs::AbstractArray)
  cx = __context__
  function accumTuple!( t1,t2,ind )
    t1[2][ind] = t2[2]
    (accum(t1[1],t2[1]), t1[2] )
  end

  function reducer( (y,df), ind)
    x = xs[ind]
    fx,back = _forward(cx,f,x)
    return y+fx, Δ -> accumTuple!( df( Δ ) , back(Δ),ind )
  end

  #f has no mutations so we can iterate in normal direction during the backward pass
  reduce( reducer, eachindex(xs), init = ( zero(eltype(xs)), Δ->( nothing, similar(xs) )  ) )
end
```

It works in the simple case, but highlight the type instability issue of not knowing the type of gradient of element beforehand. ( In the above code similar(xs) should be similar( δ map(f,xs)/δxs  )

For it to work we need to know the output type before calling forward.

It's not quadratic :)

It's using mutations :( which means we can differentiate 2 times.

**Comment by MikeInnes** [comment]
Can you explain why the current code is quadratic? Differentiating both map and sum should be efficient, so it's odd that the combination wouldn't be.

**Comment by unrealwill** [comment]
The problem lies with the accumulation inside map/sum.

Probably related to #317

The type of f(elt) can be either T, Nothing, or Union{T,Nothing}, but there is nothing to enforce that they are all the same across elements. (T can also be more complex like a struct itself, so you can have output types of {a:Nothing, b:Float64,c:Nothing} for the first element, {a:Float64,b:Nothing,c:Nothing} for the second element, {a:Nothing,b:Nothing,c:Float64} for the third element. The accumulation of which can result in a "type explosion"

For the captured variables, currently the accumulation is done via an accumulation of immutables Tuples, which julia compiler doesn't seem to know how to accumulate without a recopy at every accumulation, meaning the accumulation is quadratic with respect of the number of captured variables.

There is also the quadratic problem when doing getIndex on captured arrays, because the adjoint of getIndex doesn't return a sparse structures but a dense array.

But there would be some recopy of ~ length of the array to map each time, to change the type, of the previously computed map values, once we reach an element whose forward doesn't give the same type.
