### ISSUE TITLE
Basic Usage Fails

### ISSUE THREAD

**Issue by tawheeler** [FluxML/Zygote.jl#32]
Hello, I am having trouble with basic usage of Zygote out of the box.

```
using Zygote
f(x) = 2*x + 3
f'(2)
```

produces:
```
ERROR: MethodError: no method matching adjoint(::typeof(f))
Closest candidates are:
  adjoint(::Missing) at missing.jl:79
  adjoint(::Number) at number.jl:193
  adjoint(::LinearAlgebra.Adjoint{#s177,#s176} where #s176<:Union{StaticArray{Tuple{N},T,1} where T where N, StaticArray{Tuple{N,M},T,2} where T where M where N} where #s177) at /home/tim/.julia/packages/StaticArrays/WmJnA/src/linalg.jl:78
  ...
Stacktrace:
 [1] top-level scope at none:0
```

Other Zyogte functionality doesn't seem right either.  I got a stack trace error when trying to use `gradient`.

Are there perhaps install instructions I am missing?

Thank you!

**Comment by tawheeler** [comment]
I used `Pkg.add` to install. Turns out `] add Zygote#master` was required.

**Comment by awf** [comment]
Update as this is a top google hit: I needed ` add Zygote#master IRTools#master`
