### ISSUE TITLE
DimensionMismatch on nested for loop

### ISSUE THREAD

**Issue by hessammehr** [FluxML/Zygote.jl#320]
```julia
function f(x)
    N = 4
    for i1 in 1:3    # single loop works without issue
        for i2 in 1:N   # needs to be a variable `1:4` works fine
        end
    end
    0.0 # same error with `x`
end
```

```julia
Zygote.gradient(f, 2)
ERROR: Compiling Tuple{typeof(f),Int64}: DimensionMismatch("dimensions must match")

Zygote.gradient(f, rand(5))
ERROR: Compiling Tuple{typeof(f),Array{Float64,1}}: DimensionMismatch("dimensions must match")
```

**Comment by hessammehr** [comment]
Seems like `@code_ir` also fails for the same invocation, e.g. `@code_ir f(2)`.

**Comment by MikeInnes** [comment]
Thanks for the great test case. Just confirming I can reproduce this on master; fix hopefully incoming.

**Comment by MikeInnes** [comment]
Fixed with https://github.com/MikeInnes/IRTools.jl/commit/bb737ec9c4a6a46cd85f541ef770729d91347501.

**Comment by hessammehr** [comment]
Thanks for looking at this issue. Unfortunately, test with the same function on master now goes into an infinite loop with lots of allocation. I've confirmed this on Julia 1.1.1 and 1.3.0-rc1.

**Comment by MikeInnes** [comment]
Compiling the code, or running it? You can test by checking `@code_adjoint`.

**Comment by hessammehr** [comment]
```julia
# this runs fine
Zygote.@code_adjoint f(1.0)
# this gets stuck
Zygote.gradient(f, 1.0)
```

**Comment by Stamp1993** [comment]
I have infinite loop trying to differentiate Modia models, where I have loops calling functions containing loops, etc...

**Comment by hessammehr** [comment]
Closing this as today's IRTools commits seem to have fixed the issue.

```julia
Zygote.gradient(f, 1.0)
# (nothing,)
```
