### ISSUE TITLE
Type instability on tuple since d74f3c

### ISSUE THREAD

**Issue by unrealwill** [FluxML/Zygote.jl#322]
@MikeInnes 
Commit d74f3cf5ed3c185969ff7787ee36d15c105e6653 seems to have introduced a type instability issue on Tuple 

```
using Zygote

function h( vg )
    v = vg.v
    g = vg.g
    return v^2+g^2
end

function main()

vg = (v=1.0,g=2.0)
println( typeof(vg))

res = Zygote.gradient(h,vg)
println(res)
@code_warntype( Zygote.gradient(h,vg) )

end

main()
```

> Body::Tuple{Any}
> 1 ─ %1  = (getfield)(args, 1)::NamedTuple{(:v, :g),Tuple{Float64,Float64}}
> ...
> │   %20 = %new(typeof(∂(h)), %19)::typeof(∂(h))
> │   %21 = invoke %20(1.0::Float64)::Tuple{Nothing,Any}
> │   %22 = (getfield)(%21, 2)::Any
> │   %23 = (Core.tuple)(%22)::Tuple{Any}
> └──       return %23

**Comment by MikeInnes** [comment]
Yes, this will make more code uninferable. You can still recover that with `ZYGOTE_TYPED` if you need to.

**Comment by MikeInnes** [comment]
I undid this so it should be fixed, lmk if not.
