### ISSUE TITLE
Use forward-mode in broadcasting?

### ISSUE THREAD

**Issue by tkf** [FluxML/Zygote.jl#336]
It seems that the overhead of the way broadcastings are handled currently is quite large:

* https://github.com/FluxML/Zygote.jl/issues/323#issuecomment-533032855
* https://discourse.julialang.org/t/zygote-performance/29028/16

Would it make sense to use the ForwardDiff-based solution (`broadcast_forward`) provided that it can be handled by ForwardDiff?  That is to say:

* The function (`.f`) wrapped in all `Broadcasted`s are singleton (`Base.issingletontype`) and
* All arguments (`.args`) wrapped in all `Broadcasted`s are `Real`, `AbstractArray{<:Real}`, or non-differentiable (e.g., `Type`, `Symbol` and `Val`).

Note that, with ForwardDiff-based approach, we can fuse all broadcastings and also call style-specific materialization method.

Is this a reasonable approach?  Or would the performance improvements be implemented soon?

**Comment by MikeInnes** [comment]
Yes, I think this would be a good approach. I also would like to fill out more explicit gradients for broadcasting.

**Comment by cossio** [comment]
Does https://github.com/FluxML/Zygote.jl/pull/1001 address this?
