### ISSUE TITLE
Unexpected output for identity function

### ISSUE THREAD

**Issue by mistguy** [FluxML/Zygote.jl#34]
```julia
julia> using Zygote

julia> f(x) = x
f (generic function with 1 method)

julia> f'(1.0)
true
```

I was not expecting `true` for `f'(1.0)`.

**Comment by MikeInnes** [comment]
`true` is just another way of saying `1`; I'm using a small int type so that we avoid widening types where possible. But `Int8(1)` does the same job and looks less surprising, so I've tweaked it to use that instead.
