### ISSUE TITLE
Need convenient utilities for looking inside Grads(...)

### ISSUE THREAD

**Issue by jessebett** [FluxML/Zygote.jl#345]
`Zygote.pullback(...)[2]` is a `Grads(...)` object which has no convenient way to look at its values. This makes debugging incredibly difficult.

There are no `getindex` methods. There are no `iterate` methods. 

Unlike the old tracker way where the gradients are accumulated into the tracked object so you can look at `x.grads` there is no equivalent functionality.

If `Zygote.@showgrads` provides this functionality it is incredibly unclear. The `do` blocks aren't readable.

What is the correct way to inspect the values that have actually accumulated in `Grads(...)`?

**Comment by jessebett** [comment]
```
Grads(...)[model[1].W]
```
Is undocumented and hard to discover that this works.

**Comment by MikeInnes** [comment]
That usage is documented [in the same place as the parameter-based gradient usage](https://fluxml.ai/Zygote.jl/dev/#Gradients-of-ML-models-1) is, and works the exact same way as Flux (if you didn't get the `Grads` object by using that API, something has definitely gone wrong).

> And it requires knowing the exact struct field names for the model.

It requires that you have a reference to the original object `x`, yes, but so does the Tracker API (`model[1].W.grad`). What would the alternative be?

**Comment by jessebett** [comment]
Right so this is actually confusing and not  really documented here. I assume you're referring to the example where you index into `Grads(...)` like 
```
julia> grads = gradient(() -> sum(linear(x)), Params([W, b]))
Grads(...)

julia> grads[W], grads[b]
```

However it is not obvious to extend this to the case where gradients are taken wrt `params(model)` 

You're right that the Tracker API also has something like this. I'm not proposing an alternative, I think it is very nice. I would like better utilities to make this niceness apparent.

For one the `show` method could be more useful than `Grads(...)` not sure about that though. Is there something similar to `fieldnames` that will return the structure of the reference object? 

Really anything that makes it easier to know how to look inside of `Grads(...)`

**Comment by mcabbott** [comment]
Perhaps it could at least hint that it behaves like a Dict, and confirm that it’s got roughly as many entries as you expected? 
```
Base.show(io::IO, ps::Zygote.Grads) = print(io, "Grads(IdDict with ",length(ps.grads)," entries, total length ",sum(length, values(grads.grads)),")")
```

**Comment by jessebett** [comment]
@mcabbott's observation that it behaves like a dict, but there's no methods for `keys` and `values` (which is what I want) just returns the `Grads(...)` back.

Also, form the above snippet `Grads(...).grads` works, which I did not know! That's exactly what I wanted, just to quickly debug if my gradients are reaching all the parameters by seeing if they're zero.

**Comment by mcabbott** [comment]
Indeed, my hack doesn’t let you see whether it’s nonzero (or full of `NaN`s). Maybe it should print out `join(values(grads.grads), ", “)` or something… a bit like `Params` does.

**Comment by MikeInnes** [comment]
If you want a dictionary you can just to `IdDict(p => gs[p] for p in ps)`, where `ps` is your parameter set.

It seems like the issue here is not what `Grads` actually supports but just documenting the usage patterns for it. None of it's particularly unusual or non-standard, I think, but it's useful to have these things written down.

**Comment by MikeInnes** [comment]
Adding the docs issue as part of https://github.com/FluxML/Flux.jl/issues/891.

**Comment by rainmaker29** [comment]
> @mcabbott's observation that it behaves like a dict, but there's no methods for `keys` and `values` (which is what I want) just returns the `Grads(...)` back.
> 
> Also, form the above snippet `Grads(...).grads` works, which I did not know! That's exactly what I wanted, just to quickly debug if my gradients are reaching all the parameters by seeing if they're zero.

On calling 'Grads(...).grads' , this shows up
`TaskFailedException:
scalar getindex is disallowed`
