### ISSUE TITLE
Separate gradcheck

### ISSUE THREAD

**Issue by pevnak** [FluxML/Zygote.jl#346]
I would like to ask, if `ngradient` can live in a separate file with as few dependencies as possible. It is convenient to use when checking gradients in other packages, and importing FFTW for that is not necessary.  It can be included in tests by
```
include(joinpath(dirname(pathof(Zygote)),"..","test","gradcheck.jl"))
```

Are there opinions why not to do that?

**Comment by willtebbutt** [comment]
Is there any reason you can't just use [FiniteDifferences.jl](https://github.com/JuliaDiff/FiniteDifferences.jl) for gradient checks in other packages?

**Comment by pevnak** [comment]
I already thought about that. Does it work for multidimensional arguments? Docs talk always about scalars.

**Comment by willtebbutt** [comment]
Yup. We have `grad` and `jacobian` functions. For some reason they're buried in the API section of the documentation. Someone should really do something about that...

We also have `jvp` (forwards-mode equivalent) and `j'vp` (reverse-mode equivalent) functions if you're testing AD-related stuff.

**Comment by pevnak** [comment]
Nice, I see, thanks a lot, looks gorgeous.
