### ISSUE TITLE
Splatting and mutation?

### ISSUE THREAD

**Issue by marcoct** [FluxML/Zygote.jl#347]
I ran into some unexpected `nothing`s that depend on whether splatting was used or not.

I tried simplifying it into a minimal example---it seems like the problem might involve some combination of splatting and mutation.

```julia
import Zygote

mutable struct MyMutable
    value::Float64
end

function foo!(m::MyMutable, x)
    m.value = x
end

function baz(args)
    m = MyMutable(0.)
    # foo!(m, args[1]) # grad(1.) works as expected
    foo!(m, args...) # grad(1.) gives 'nothing'
    m.value
end

value, grad = Zygote.pullback(baz, (1.0,))
@assert grad(1.) == ((1.0,),)
```

PS: Zygote looks like great work, and we're looking forward to using it for AD within https://github.com/probcomp/Gen/

**Comment by DoktorMike** [comment]
I'm looking forward to this too as it will combine two of my favorite projects in julia. 😊 Will follow this!

**Comment by MikeInnes** [comment]
Your analysis is spot on -- `Core._apply` just assumed that `f` was pure, so didn't bother calling its adjoint with `nothing` as input. Thanks for the report and nice test case.

Glad to hear you're looking at this for Gen!
