### ISSUE TITLE
ZygoteRules compat

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#392]
v0.3.4 doesn't work correctly with ZygoteRules v0.2.0 due to the `forward` -> `pullback` name change. Would be very helpful if @MikeInnes could publish v0.3.5 of Zygote that upper bounds that dependency so that stuff doesn't break while the ecosystem upgrades.

**Comment by MikeInnes** [comment]
I think we can just edit the current compat bounds in the registry.

**Comment by zenna** [comment]
I think a few people have been hit by this today.  I think a combination of these version issues is making some packages (Flux, Turing) broken at the moment for people who updated today.

**Comment by MikeInnes** [comment]
Opened https://github.com/JuliaRegistries/General/pull/5065

**Comment by McCoyBecker** [comment]
I just opened a new issue without reading this one, apologies:
https://github.com/FluxML/Zygote.jl/issues/396

Posted about on Turing:
https://github.com/TuringLang/Turing.jl/issues/936

**Comment by MikeInnes** [comment]
Bounds PR has gone through, so should be fixed.
