### ISSUE TITLE
Is it possible to calculate array assignments? How?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Zygote.jl#40]
Is it possible to make this work?

```julia
function foo(x)
     z = zero(x)
     for i in eachindex(x)
           z[i] = x[i]
      end
       z
end

gradient(x->sum(foo(x)), rand(10)) # this gives unsupported control flow error at the moment
```

I would love to help implement this if this is possible, but anyone can tell if this is possible? and how?

I know it would be quite hard for operator overloaded AD, but maybe this is much easier here?

**Comment by antoine-levitt** [comment]
There seems to be ongoing work on that: https://discourse.julialang.org/t/chainrules-replacing-diffrules-in-the-julia-ad-world/17608/42, https://github.com/FluxML/Zygote.jl/branches

**Comment by Roger-luo** [comment]
I see....

**Comment by MikeInnes** [comment]
Indeed there is.

```julia
julia> function foo(x)
         z = zero(x)
         for i in eachindex(x)
           z[i] = x[i]
         end
         return z
       end
foo (generic function with 1 method)

julia> gradient(x -> sum(foo(x)), [1, 2, 3])
([1, 1, 1],)
```

This is on `Zygote#mutate`, and you'll also need julia master to avoid the control flow issue.

**Comment by MikeInnes** [comment]
Closing in favour of #61
