### ISSUE TITLE
Jacobian in Zygote with Params

### ISSUE THREAD

**Issue by theogf** [FluxML/Zygote.jl#413]
I simply love the Flux+Zygote flexibility for extracting parameters from object and get the appropriate gradients directly in the same structure (`Grads`).
However it would be nice to have the same feature for `jacobian`s with `Params`. I saw the already open issues #98 and #51. But the proposed workaround is only valid for arrays.

**Comment by MikeInnes** [comment]
It'd make some sense to do jacobians this way. You could build it on top of gradients pretty easily, I think.

**Comment by mcabbott** [comment]
I doodled something together a little while ago, [link](https://github.com/FluxML/Zygote.jl/compare/master...mcabbott:jacobian), maybe I should make a PR...
