### ISSUE TITLE
softmax adjoint does not support the dims keyword

### ISSUE THREAD

**Issue by tanhevg** [FluxML/Zygote.jl#425]
softmax in NNlib#master already supports the dims keyword (which is awesome). Zygote `@adjoint` still does not support this. Should be trivial to add - let me know if you'd like a PR on this.

**Comment by MikeInnes** [comment]
Yes, a PR would be great, thanks.

**Comment by tanhevg** [comment]
#443

**Comment by tanhevg** [comment]
The pull request is merged, but the bug is not fixed. Need to re-release NNlib and bump the dependency.

**Comment by CarloLucibello** [comment]
closing since everything is fixed on master, will release new versions soon
