### ISSUE TITLE
Gradient of inv and logdet UpperTriangular matrix is not UpperTriangular

### ISSUE THREAD

**Issue by aterenin** [FluxML/Zygote.jl#431]
For sparse Gaussian processes, one often wants to parametrize the variational distribution using its Cholesky factors, which form an upper-triangular matrix and are trainable.

However, when taking gradients, Zygote instead computes the gradient with respect to all entries in the UpperTriangular matrix, including ones that are set to zero by virtue of it being UpperTriangular. This is related to #163.

For the moment, a workaround suitable for training models is to simply call `UpperTriangular(x)` on the upper-triangular matrix `x` before using it.

**Comment by sdewaele** [comment]
Perhaps this is more related to #402. As an alternative you could insert the projection function ℙ in your code, see https://github.com/FluxML/Zygote.jl/issues/402#issuecomment-559629555. Then, the adjoint will be an `UpperTriangular`.
