### ISSUE TITLE
Make Zygote handle invoke

### ISSUE THREAD

**Issue by Keno** [FluxML/Zygote.jl#44]
Flux.jl now uses invoke in its dense layer, which Zygote doesn't handle, breaking VGG. We should fix that by supporting invoke in Zygote.

**Comment by staticfloat** [comment]
Seconded; this is preventing my using Zygote with pretty much any Flux model right now.

**Comment by staticfloat** [comment]
@MikeInnes It looks like you pushed a test, but not the actual code to deal with `invoke()`?

With https://github.com/FluxML/Zygote.jl/pull/58 and running the tests locally, the added test fails.

**Comment by MikeInnes** [comment]
Changes required are here – https://github.com/MikeInnes/IRTools.jl/commit/80fffa13a83d0c24e72a59ca507d9b2135651e48. As long as you have that commit it should work, but we should fix the manifest anyway.

**Comment by staticfloat** [comment]
Confirmed that `IRTools#master` works.  I've updated #58 accordingly
