### ISSUE TITLE
Zygote fails when an adjoint hits the GC

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Zygote.jl#451]
Because then the gc_preserve_end part of the array definition is hit. MWE:

```julia
using Zygote
function f(a)
  GC.@preserve a begin
  end
  sum(a)
end
Zygote.gradient(f,rand(5))
```

**Comment by MikeInnes** [comment]
It's expected that Zygote will fail to differentiate GC preserves since we can't differentiate C wrappers anyway, you just have to add an adjoint. It's possible that's there's a different issue going on in DiffEqFlux, but if so this doesn't represent it.
