### ISSUE TITLE
Readme Error

### ISSUE THREAD

**Issue by azev77** [FluxML/Zygote.jl#470]
```Julia
julia> fs = Dict("sin" => sin, "cos" => cos, "tan" => tan);

julia> gradient(x -> fs[readline()](x), 1)
##The code freezes here. 

##But, the following is correct
julia> gradient(x -> sin(x), 1)

```

**Comment by Paethon** [comment]
Are you sure the code freezes? After this line you are supposed to enter the name of one of the trigonometric functions on the keyboard (sin, cos, tan)

**Comment by dhairyagandhi96** [comment]
Yup, the user has to give in the input

**Comment by azev77** [comment]
I see. 
It works in REPL is I type `sin` in the line below gradient. 

However, it doesn't work in Juno for some reason
