### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by rapus95** [FluxML/Zygote.jl#484]
Well, since Flux 0.10 the future is here and the Zygote readme at least partially doesn't make a lot of sense anymore.

> You probably don't want to use Zygote yet (except as a preview of the future). Instead use Flux's built-in AD, which is API-compatible, and at some point in the near future you'll get a free speed boost.

While the former sentence would be contrary to the decision made in Flux, the first part of the latter sentence is true by tautology and the last part hopefully still true.

P.S. I know you know that but as it's a minor flaw this shall only be a friendly reminder for you aswell as the information for people who come along and wonder whether that's correct. It's not 😄

**Comment by MikeInnes** [comment]
Thanks for bringing this up, I've made a bunch of quick changes.
