### ISSUE TITLE
Zygote suffers poor performance w/ type conversions

### ISSUE THREAD

**Issue by mkschleg** [FluxML/Zygote.jl#491]
I'm unsure if this is a known issue (and wasn't able to find this directly in any of the issues boards), but something I've seen in my own code and I believe is the cause to some of the complaints of zygote being slow in the Flux issues board. For some details see this comment: https://github.com/FluxML/Flux.jl/issues/815#issuecomment-580830737.

Here is a MWE using Flux#0.10.0 and Benchmark tools:
```julia
julia> using Flux, BenchmarkTools
julia> function func(input_type)
           W = rand(Float32, 1024, 1024)
           x = rand(input_type, 1024, 64)
           y = rand(Float32, 1024, 64)
           @btime gradient(()->Flux.mse($W*$x, $y), Flux.params($W))
       end

func (generic function with 1 method)

julia> func(Float64)
  134.298 ms (655590 allocations: 29.01 MiB)
Grads(...)

julia> func(Float32)
  15.503 ms (655584 allocations: 18.01 MiB)
Grads(...)
```

**Comment by oxinabox** [comment]
Lets take Zygote out of the equation, by not doing any gradient op:

```
julia> function func_primal(input_type)
          W = rand(Float32, 1024, 1024)
          x = rand(input_type, 1024, 64)
          y = rand(Float32, 1024, 64)
          @btime Flux.mse($W*$x, $y)
       end
func_primal (generic function with 1 method)

julia> func_primal(Float32);
  439.918 μs (4 allocations: 512.16 KiB)

julia> func_primal(Float64)
  52.352 ms (10 allocations: 1.00 MiB)
```

So for the primal function it is about 160x slower if you mix types.

Now redoing the timing of the gradient on my computer i get:
```
julia> func(Float32)
  12.317 ms (655584 allocations: 18.01 MiB)

julia> func(Float64);
  131.583 ms (655590 allocations: 29.01 MiB)
```

so mixing types is about 11x slower.

Which is much better than the slow-down in the of the primal problem.

And at least from the surface of looking at `@code_typed` Zygote isn't doing anything different between them.
Its not making something great -- type inference is failing in *both* cases.

**Comment by mkschleg** [comment]
Right. And looking at the docs for Flux again, this is stated in the performance tips (preserve types of your inputs). I just wonder if this needs to be highlighted in the docs earlier on. As this doesn't seem to be an issue with Zygote, maybe this discussion would be better in the originating issue. So I'm going to close this and restate the need for this to be highlighted over to the other issue.
