### ISSUE TITLE
How to calculate Jacobians (or just derivatives of vector functions) with Zygote?

### ISSUE THREAD

**Issue by Krastanov** [FluxML/Zygote.jl#51]
Why does
```julia
Zygote.forward(a -> [2.,1.]*a, 1)[2](1)
```
return `3` instead of `[2,1]`?

Am I missing a big philosophical or computational reason for the omission of non-scalar functions? Zygote is doing a form of forward AD, so the derivative of a function that maps a scalar to a vector should be cheap, right?

**Comment by MikeInnes** [comment]
Zygote is reverse mode, so the output of `forward` calculates a vector-Jacobian product. For forward you should probably check out ForwardDiff.jl.

It would be good to add utilities for full Jacobians though.

**Comment by MikeInnes** [comment]
Incidentally it's easy to do forward-over-reverse with Zygote's API.

```julia
using Flux

y, back = Tracker.forward(x -> [3x^2, 5x+2], 5)

Tracker.gradient(x -> back(x)[1], [1, 1]) # [30, 5]
```

This probably won't actually work with Zygote yet, since nested AD doesn't work in all cases, but it will eventually.
