### ISSUE TITLE
deprecate dropgrad

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Zygote.jl#536]
Now that #465 has been merged, we have two functions, `dropgrad` and `nograd` doing the same thing. 

I prefer `nograd`, since it makes a better pair with `@nograd`. If people agree, we should add a comment above `dropgrad`  `# TODO: set for deprecation in v0.5` and then follow up with the deprecation. 

If we decide to stick to `dropgrad`, we should remove `nograd` before next release is tagged

**Comment by MikeInnes** [comment]
We should remove `nograd`. `dropgrad` does something different since it affects values, not blocks of code (which was the original proposal in #465).

**Comment by cossio** [comment]
> `dropgrad` does something different since it affects values

I don't see how `nograd(...)` (as currently defined) is different from `dropgrad`?

**Comment by MikeInnes** [comment]
As currently defined it's the same, yes, which is why we should get rid of it. Something like the `nograd` originally defined in #465 would still be useful, though, since it would help us handle mutations in the forward pass.
