### ISSUE TITLE
add `@nograd` block

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Zygote.jl#537]
As suggested in #465,  it can be of some use the possibility to add blocks of code where gradients are not computed (detached) and mutations are allowed. The proposed syntax is
```julia
@nograd begin
    ...
end
```

**Comment by MikeInnes** [comment]
I still think we should just call this `Zygote.ignore` (or `Zygote.@ignore`; we can have both). It should be pretty clear then that you're just asking Zygote to ignore that block of code.

Consistency with `@nograd` isn't too important as we want to get rid of it eventually anyway.
