### ISSUE TITLE
getindex with nothing in differential

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#546]
This currently breaks things:
```julia
_, back = Zygote.pullback(getindex, randn(4), [1])
back([nothing])
```

edit: yields error:
```julia
ERROR: MethodError: convert(::Type{Union{}}, ::Bool) is ambiguous. Candidates:
  convert(::Type{Union{}}, x) in Base at essentials.jl:166
  convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7
  convert(::Type{T}, arg) where T<:VecElement in Base at baseext.jl:8
  convert(::Type{T}, x::Number) where T<:AbstractChar in Base at char.jl:179
Possible fix, define
  convert(::Type{Union{}}, ::Number)
Stacktrace:
 [1] convert(::Type{Nothing}, ::Bool) at ./some.jl:34
 [2] fill!(::Array{Nothing,1}, ::Bool) at ./array.jl:309
 [3] _zero(::Array{Float64,1}, ::Type) at /Users/willtebbutt/.julia/packages/Zygote/S1EoU/src/lib/array.jl:33
 [4] (::Zygote.var"#1025#1027"{Array{Float64,1},Tuple{Array{Int64,1}}})(::Array{Nothing,1}) at /Users/willtebbutt/.julia/packages/Zygote/S1EoU/src/lib/array.jl:45
 [5] (::Zygote.var"#2710#back#1021"{Zygote.var"#1025#1027"{Array{Float64,1},Tuple{Array{Int64,1}}}})(::Array{Nothing,1}) at /Users/willtebbutt/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [6] (::Zygote.var"#38#39"{Zygote.var"#2710#back#1021"{Zygote.var"#1025#1027"{Array{Float64,1},Tuple{Array{Int64,1}}}}})(::Array{Nothing,1}) at /Users/willtebbutt/.julia/packages/Zygote/S1EoU/src/compiler/interface.jl:36
 [7] top-level scope at REPL[8]:1
```

**Comment by MikeInnes** [comment]
Happening because we try to do an [in-place update](https://github.com/FluxML/Zygote.jl/blob/f16d85637a651d19371d88ae96e3f82a666202d4/src/lib/array.jl#L40) of the gradient rather than `accum`-ing it. We just need to tweak that code to strip out zeros.

**Comment by willtebbutt** [comment]
Okay. What's the correct output here? Do we want to return an array of `nothing`s, or make the `nothing`s zero? Or some other option?

**Comment by MikeInnes** [comment]
Would be good to see the error, but I imagine the specific problem is [this line](https://github.com/FluxML/Zygote.jl/blob/f16d85637a651d19371d88ae96e3f82a666202d4/src/lib/array.jl#L33). We make a gradient array based on the eltype of `dy`, which is right, but also assume it's numeric (we can fill it with `false`). We just need a dispatch for non-numeric `T` similar to the definition of `_zero` just below that line.

**Comment by willtebbutt** [comment]
> Would be good to see the error

Lol sorry 🤦‍♂ . Have now added to original comment.

Here's how I understand the problem. Letting `T` be the element type of `x`, its about finding an appropriate zero-type for `T`.

### Numeric case:

The `zero` element for a given type `T` is assumed to be of that type. eg. for `Float64`, the zero element is `0.0`, which is a subtype of `Float64`.

In this case is makes sense to me that you would choose to coerce nothings into zeros.

### `Any` case:

Assuming that we know nothing special about `T`, the appropriate zero element is (currently) `nothing`. It therefore seems appropriate to represent the differential using an `Array{Union{Nothing, eltype(dy)}}`.

### Upshot

- I don't believe it's appropriate the always make the element type of `dx` the same as the element type of `dy` because it doesn't make sense for types where the zero element isn't the same type as the differential.
- We probably need to have separate behaviour implemented for `x`s with numeric element types, and those without.

**Comment by MikeInnes** [comment]
Focusing on the numeric case, the main issue with using `eltype(x)` is that `eltype(dy)` might be a wider type (for example, a complex number). That's the reason for the current choice of using `eltype(dy)`. We might have to do something like `promote_type(eltype(x), eltype(dy))` with a sensible fallback when `eltype(dy) == Nothing`.

Looking at your error I'm not sure where the `Union{}` eltype is coming from though; that seems suspicious and would be worth narrowing down.

**Comment by willtebbutt** [comment]
I agree regarding the numeric case -- I would imagine that the appropriate fallback is probably `zero(T)`.

> Looking at your error I'm not sure where the Union{} eltype is coming from though; that seems suspicious and would be worth narrowing down.

I'll dig into it a little bit more this evening.

**Comment by willtebbutt** [comment]
Okay, so it turns out that my assessment of the situation was exactly the same as whoever it was that wrote the code in the first place 😂 . Turns out that there weren't a lot of changes that need to be made, and your original intuition about needing to use `accum` was correct.
