### ISSUE TITLE
@nograd println

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#548]
Is there a good reason not to `@nograd` `Base.println` and `Core.println`?

**Comment by CarloLucibello** [comment]
are those falling back to `show`? maybe we should nograd `show`

**Comment by willtebbutt** [comment]
It's probably best to do both. Assuming that its safe to nograd `println` it will just improve compile times.

@nickrobinson251 do you have any thoughts on this?

**Comment by nickrobinson251** [comment]
Sounds reasonable to me
