### ISSUE TITLE
Output from `pullback` doesn't match result from original function

### ISSUE THREAD

**Issue by AdarshKumar712** [FluxML/Zygote.jl#583]
Here is a MWE for mentioned problem:
```
julia> m = Chain(Conv((3,3), 1=>3), BatchNorm(3))
Chain(Conv((3, 3), 1=>3), BatchNorm(3))

julia> x = ones(4,4,1,1)
4×4×1×1 Array{Float64,4}:
[:, :, 1, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> m(x)
2×2×3×1 Array{Float64,4}:
[:, :, 1, 1] =
 0.067747  0.067747
 0.067747  0.067747

[:, :, 2, 1] =
 -0.0623291  -0.0623291
 -0.0623291  -0.0623291

[:, :, 3, 1] =
 -0.791398  -0.791398
 -0.791398  -0.791398

julia> out, back = Zygote.pullback(m, x)
([0.0 0.0; 0.0 0.0]

[0.0 0.0; 0.0 0.0]

[0.0 0.0; 0.0 0.0], Zygote.var"#38#39"{typeof(∂(λ))}(∂(λ)))
```
However, I suppose the `pullback` should return result from original function as the first output (as given in docs),  which is not the same as `m(x)`. Please do correct me if I am wrong.

**Comment by oxinabox** [comment]
It should be the same up to numerical accuracy.

The fact that it is all zero seems rather odd to me

**Comment by mcabbott** [comment]
Is this obviously wrong? That layer has a lot of parameters, and tests `istraining()` here:

https://github.com/FluxML/Flux.jl/blob/7a32a703f0f2842dda73d4454aff5990ade365d5/src/layers/normalise.jl#L180

Simpler example:
```julia
julia> d = Dropout(0.5);

julia> d(ones(Int,10)) |> println
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

julia> Zygote.pullback(d, ones(Int, 10))
([0, 0, 2, 0, 0, 2, 0, 0, 2, 2], Zygote.var"#36#37"{typeof(∂(λ))}(∂(λ)))
```

**Comment by AdarshKumar712** [comment]
@mcabbott Is it possible to set `istraining()` as `false` while using `pullback`?

**Comment by mcabbott** [comment]
It looks like `_isactive(m)` checks a field of the struct before calling `istraining()`, presumably included for this purpose:

https://github.com/FluxML/Flux.jl/blob/7a32a703f0f2842dda73d4454aff5990ade365d5/src/layers/normalise.jl#L5

**Comment by AdarshKumar712** [comment]
Yes, it works. Thanks! :)
I am closing this issue, as it is resolved now. Thanks for your help!
