### ISSUE TITLE
Array Indexing Error

### ISSUE THREAD

**Issue by lhnguyen-vn** [FluxML/Zygote.jl#597]
I ran into a Zygote bug related to array slicing. Here's a MWE:
```
array = [[1,2], [3,4], [5,6]]
_, back = Zygote.pullback(x -> x[1:2], array)
back([[1,1], [1,1]]) # MethodError: no method matching +(::Nothing, ::Array{Int64,1})
```
This is a relatively well-known issue, Zygote uses `nothing` as a stronger zero. Internally, this is the source of the error:
https://github.com/FluxML/Zygote.jl/blob/17a017f1e70e7156b5746000ec20bb29c52de553/src/lib/array.jl#L45-L47
Shouldn't the last line just be `dxv .= _droplike(dy, dxv)`? This gives the correct behavior and I can't think of why one would want to add to an array filled with `nothing` instead?

**Comment by lhnguyen-vn** [comment]
On second thoughts, `.+=` is correct. Perhaps `_zero` should be extended for arrays of arrays, something along the line of 
```
_zero(xs::AbstractArray{<:AbstractArray}, T=Any) = [_zero(x) for x in xs]
```
This gives the correct gradient for my case, and I notice also solves issue #454.

**Comment by AzamatB** [comment]
This seems to be fixed on master.
