### ISSUE TITLE
Zygote 0.4.17 breaks broadcast of Params

### ISSUE THREAD

**Issue by devmotion** [FluxML/Zygote.jl#617]
It seems https://github.com/FluxML/Zygote.jl/pull/611 breaks broadcasting of `Params`. We've seen test errors in KernelFunctions with Zygote 0.14.7 that do not appear on Zygote 0.14.6 (see https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/95#issuecomment-619378841). A simple example:
```julia
julia> using Zygote

julia> x = [0]

julia> p = Params([x])
```
On Zygote 0.4.17 I get
```julia
julia> length.(p)
ERROR: MethodError: no method matching ndims(::Type{Params})
Closest candidates are:
  ndims(::Base.Generator) at generator.jl:53
  ndims(::Number) at number.jl:67
  ndims(::Type{#s69} where #s69<:Number) at number.jl:68
  ...
Stacktrace:
 [1] Base.Broadcast.BroadcastStyle(::Type{Params}) at ./broadcast.jl:103
 [2] combine_styles(::Params) at ./broadcast.jl:410
 [3] broadcasted(::Function, ::Params) at ./broadcast.jl:1232
 [4] top-level scope at REPL[4]:1
```
whereas on Zygote 0.4.16
```julia
julia> length.(p)                               
1-element Array{Int64,1}:                     
 1 
```

**Comment by CarloLucibello** [comment]
Didn't know that Params supported broadcast. Can fix the error implementing
```julia
Base.broadcasted(f, ps::Params) = broadcasted(f, ps.order)
```
if that's what we want. I would be in favor. Workaround is
```julia
[f(p) for p in ps]
```
I would also add `getindex` but looking at the comment in
```julia
# TODO store ids only
struct Params
  order::Buffer{Any, Vector{Any}}
  params::IdSet{Any}
  Params() = new(Buffer([], false), IdSet())
end
```
the long term plan may be to have a set-like interface

**Comment by dhairyagandhi96** [comment]
Can we quickly add tests for broadcasting on Params

**Comment by cossio** [comment]
@devmotion Is there a typo in your example? Shouldn't it be

```
using Zygote
x = [0]
p = Params.([x])  # notice the .
length.(p)  # works fine
```

**Comment by devmotion** [comment]
No, there's no typo, because otherwise you just call `length` on `Params`, so no broadcasting of `Params` is involved, if I'm not mistaken. Maybe the example is a bit stupid but as you can see in the linked issue in KernelFunctions the latest version of Zygote clearly broke broadcasting of `Params`. In KernelFunctions we test our implementation of `Flux.trainable` for the kernels defined in the package with statements such as `all(Flux.params(kernel) .== Flux.params([γ]))` - this works without any problems up to Zygote 0.4.16 but is broken with Zygote 0.4.17.

**Comment by devmotion** [comment]
Unfortunately https://github.com/FluxML/Zygote.jl/pull/622 did not fix broadcasting of Params completely, the tests (e.g., https://travis-ci.com/github/JuliaGaussianProcesses/KernelFunctions.jl/jobs/325639931) are still broken on Zygote 0.4.18.
