### ISSUE TITLE
Splatting

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#62]
This currently fails silently:
```julia
using Zygote
y, back = Zygote.forward(x->(x...,), [1, 2, 3])
back((1, 1, 1))
```
Presumably the answer should just be `([1, 1, 1],)`, or even `((1, 1, 1),)`. It is currently `(1,)`.

**Comment by MikeInnes** [comment]
Just forgot that you can splat things other than tuples – fixed.
