### ISSUE TITLE
Gradient doubling

### ISSUE THREAD

**Issue by MikeKlocCZ** [FluxML/Zygote.jl#687]
I have encountered a gradient doubling problem with Zygote. Here is a MWE

```julia
using Flux

model=Dense(1,1,identity)
model.W[1]=2.0f0
model.b[1]=1.0f0
p1,re=Flux.destructure(model)
u0=[2.0f0]
### with a simple NN
function simple(p1)
   p2=re(p1)(u0)
   sum(p2-u0)
end
### without the NN
function simple_no_net(p1)
   p2=p1[1].*u0.+p1[2]
   sum(p2-u0)
end

θ=Flux.params(p1)
gs1 = gradient(θ) do
   simple(p1)
end
println("grads:", gs1[p1] ) #Float32[4.0, 2.0] ...#doubled

using ForwardDiff
ForwardDiff.gradient(simple,p1) ##Float32[2.0, 1.0] ...#OK

gs2 = gradient(θ) do
   simple_no_net(p1)
end
println("grads no NN:",gs2[p1]) #Float32[2.0, 1.0] ...#OK
```
This is the same issue as discussed  [here](https://github.com/SciML/DiffEqSensitivity.jl/issues/271#issue-634820719) but apparently belongs to Zygote.jl .

**Comment by oxinabox** [comment]
I have reproduced this on my computer.
Also it persists if I wrap the whole thin in a `let` block, so it is not simply a global variable thing.

**Comment by cossio** [comment]
Fixed in https://github.com/FluxML/Zygote.jl/pull/688. Someone close this?
