### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Zygote.jl#690]
There's a lot of things to tag in here, like https://github.com/FluxML/Zygote.jl/pull/662 which fixes problems dependency handling. It would be good to get a tag out.

**Comment by CarloLucibello** [comment]
we should, also this likely going to be the last release with julia 1.0 support (due to #673).  Speaking of which, we have a chain rule related error on julia 1.0 that has popped out lately, see https://travis-ci.org/github/FluxML/Zygote.jl/jobs/699307544. @oxinabox you have any clues on that?

**Comment by oxinabox** [comment]
It's not clear if that is actually a ChainRules thing or if it is just happens to be hit in that test that is with ChainRules.
That test hits a extra nasty bit of nested AD. That was breaking for ChainRules during the PR, but probably should not be in that file anymore
