### ISSUE TITLE
wrong gradient type when dividing by integer

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Zygote.jl#727]
When performing division of a Float32 by an Int I get a Float64 gradient
```julia
julia> using Zygote

julia> gradient(x -> x/2, 1f0)
(0.5,)
```
@oxinabox @MikeInnes @sethaxen @DhairyaLGandhi any clue of when was this introduced?

This is causing https://github.com/FluxML/Flux.jl/issues/1269 and possibly also https://github.com/FluxML/Flux.jl/issues/1255

**Comment by CarloLucibello** [comment]
Is [this](https://github.com/JuliaDiff/ChainRules.jl/blob/dc3db4a2ad8cfdc8227735870a7436f575d5cb3f/src/rulesets/Base/fastmath_able.jl#L136) the rule used? Should we replace it with
```julia
@scalar_rule x / y (one(x)/y, -((x / y) / y))
```
or something similar?

**Comment by sethaxen** [comment]
Yeah, that's the culprit:
```julia
julia> z, back = rrule(/, 1f0, 2)
(0.5f0, ChainRules.var"#575#/_pullback#149"{Float32,Int64}(1.0f0, 2))

julia> back(1)
(Zero(), 0.5, -0.25f0)
```

Your proposed change looks right to me. `inv` is just too problematic for promoting everything to Float64 or higher, and we should probably just remove it from all `@scalar_rrule`s.

**Comment by mcabbott** [comment]
Also fixed in https://github.com/JuliaDiff/DiffRules.jl/pull/46, but without a test it seems.

**Comment by DhairyaLGandhi** [comment]
+1 on removing dependency on `inv`
