### ISSUE TITLE
Wrong gradient through hypergeometric function pFq

### ISSUE THREAD

**Issue by bertschi** [FluxML/Zygote.jl#796]
Zygote gives wrong gradients for

```{julia}
using HypergeometricFunctions
using Zygote
import ForwardDiff

f(z) = pFq([0.1], [0.2], z)
## Parameters don't matter ... gradient also wrong for other values

gradient(f, 100.2)
## Gives (46.42500000000001,)
ForwardDiff.gradient(f ∘ first, [100.2])
## Gives [9.993752431780506e42] -- Note: ForwardDiff.gradient only defined for vector functions
```
A quick numeric check suggests that ForwardDiff is correct. Unfortunately the example is certainly far from minimal. Would be happy for suggestions on how to track down this issue.

**Comment by mcabbott** [comment]
```
julia> gradient(f, 0.75)[1]
0.84375

julia> ForwardDiff.derivative(f, 0.75)
1.0029644434748202

julia> @which  pFq([0.1], [0.2], 100.2)
pFq(α::AbstractArray{T,1} where T, β::AbstractArray{T,1} where T, z; kwds...) in HypergeometricFunctions at /Users/me/.julia/packages/HypergeometricFunctions/vfGlc/src/generalized.jl:8
```

This leads to this little function, seems too simple for much to go wrong? Maybe it would be worth replacing the for-loops with simple statements (and possibly changing the names, rather than updating the same variable) to see if anything changes?

https://github.com/JuliaMath/HypergeometricFunctions.jl/blob/5866fe52e6d2cf61b311936becb6def057ddf22a/src/specialfunctions.jl#L456

**Comment by bertschi** [comment]
Thanks, I finally boiled it down to a simpler example. It appears that variables within the while loop get conflated in Zygote's backward pass ... the for loops appear not to be a problem.

```{julia}
function ggFoo(z::Float64)
    x = 1.0
    y = 1.0 + z
    j = 1
    while abs(x - y) > 1e-6
        ## x, y = y, (x + y) / 2
        ## Same issue with explicit temporary
        tmp = (x + y) / 2
        x = y
        y = tmp
        j += 1
        println([j, x, y])
    end
    return y
end
```

```{julia}
julia> ggFoo(2.0)
[1.0, 1.0, 3.0]
[2.0, 3.0, 2.0]
[3.0, 2.0, 2.5]
...
[22.0, 2.333333969116211, 2.3333330154418945]
2.3333330154418945

julia> gradient(ggFoo, 2.0)
[1.0, 1.0, 3.0]
[2.0, 2.0, 2.0]  ## This should be [2, 3.0, 2.0] as in the forward pass!
(0.5,)
```

**Comment by MariusDrulea** [comment]
> Thanks, I finally boiled it down to a simpler example. It appears that variables within the while loop get conflated in Zygote's backward pass ... the for loops appear not to be a problem.
...............
> 
> julia> gradient(ggFoo, 2.0)
> [1.0, 1.0, 3.0]
> [2.0, 2.0, 2.0]  ## This should be [2, 3.0, 2.0] as in the forward pass!
> (0.5,)
> ```

I tried this example today and I get [2, 3.0, 2.0], just like in the forward pass. Looks like the issue was fixed in the meantime. Close the issue?

**Comment by CarloLucibello** [comment]
we can close but it would nice to add this to the tests

**Comment by bertschi** [comment]
Thanks for taking this up again.
Have just submitted a pull request with a corresponding test.
