### ISSUE TITLE
word choice in README

### ISSUE THREAD

**Issue by JeffreySarnoff** [FluxML/Zygote.jl#8]
"Despite its performance, Zygote supports the full flexibility and dynamism of the Julia language."
  Despite? maybe:

Zygote supports the full flexibility and dynamism of the Julia language.
Zygote supports the full flexibility, dynamism, and performance of the Julia language.
Zygote supports the full flexibility and dynamism of the Julia language without runtime overhead.
Zygote supports the full flexibility and dynamism of the Julia language.  Runtimes are unchanged.
Zygote supports the full flexibility and dynamism of the Julia language. Runtime costs are negligible.

**Comment by MikeInnes** [comment]
Tweaked the wording a bit.
