### ISSUE TITLE
Provide Flux-compatible training interface

### ISSUE THREAD

**Issue by jpsamaroo** [FluxML/Zygote.jl#80]
Per the code shared in https://github.com/FluxML/Flux.jl/pull/607#issuecomment-461821866:

```
# Inputs: model, xs, ys, opt 
θ = params(model)
for (x,y) in zip(xs, ys)
  dθ = gradient(θ) do
    ŷ = model(x)
    sum((y - ŷ).^2)
  end
  update!(opt, θ, dθ)
end
```

There should be a way to do training that's compatible with both Zygote and Flux, in the style of the above example. This would allow users to test both Zygote and Flux's AD implementations easily, and make the transition between the two much easier.

**Comment by MikeInnes** [comment]
On Flux master this should pretty much just work. Can you try it and report any issues you encounter?

**Comment by jpsamaroo** [comment]
Works perfectly! An example for anyone looking at this who wants a working example:

```
using Flux
using Zygote
using Statistics

opt = ADAM()
xs = [rand(8) for i in 1:10]
ys = deepcopy(xs)
model = Dense(8,8)
θ = Flux.params(model)

loss(x,y) = Flux.mse(model(x),y)
acc() = mean([loss(x,y) for (x,y) in zip(xs,ys)])

println("Flux")
for (x,y) in zip(xs,ys)
  dθ = Flux.Tracker.gradient(θ) do
    ŷ = model(x)
    sum((y - ŷ).^2)
  end
  Flux.Tracker.update!(opt, θ, dθ)
  @show acc()
end

println("Zygote")
for (x,y) in zip(xs,ys)
  dθ = Zygote.gradient(θ) do
    ŷ = model(x)
    sum((y - ŷ).^2)
  end
  Flux.Tracker.update!(opt, θ, dθ)
  @show acc()
end
```
