### ISSUE TITLE
Broken methods(Base.show)

### ISSUE THREAD

**Issue by racinmat** [FluxML/Zygote.jl#808]
```julia
using Zygote
methods(Base.show)
```
is broken, causes
```julia
[97] Error showing value of type Base.MethodList:
ERROR: UndefVarError: S not defined
Stacktrace:
 [1] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Type{
SYSTEM (REPL): showing an error caused an error
ERROR: UndefVarError: S not defined
Stacktrace:
 [1] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Type{
SYSTEM (REPL): caught exception of type UndefVarError while trying to handle a nested exception; giving up
```

**Comment by racinmat** [comment]
I tried to find root cause by installing dependencies of Zygote one by one, 
I got there
````
Status `C:\Projects\something\zygote_like_env\Project.toml`
  [4c555306] ArrayLayouts v0.4.8
  [082447d4] ChainRules v0.7.24
  [7869d1d1] IRTools v0.4.1
  [bdcacae8] LoopVectorization v0.8.26
  [1914dd2f] MacroTools v0.5.5
  [ae029012] Requires v1.1.0
  [700de1a5] ZygoteRules v0.2.0
```
and none of these dependencies cause it.

**Comment by racinmat** [comment]
By restarting Julia, calling `using Zygote` starting with fully commented-out contents. of `Zygote.jl` and uncommenting it line by line, restarting Julia and repeating this process, I found out
https://github.com/FluxML/Zygote.jl/blob/master/src/compiler/show.jl#L13 is causing the problem. When all code above it was uncommented, it worked, but running this method definition causes the error.

**Comment by KristofferC** [comment]
It should use `@isdefined`

**Comment by racinmat** [comment]
Yeah, seems like the commit that was supposed to fix it didn't add it https://github.com/FluxML/Zygote.jl/commit/9920965e6984a9f28b8445cbefa62e5b5111e84e
