### ISSUE TITLE
Move over adjoints from Flux

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Zygote.jl#81]
Flux has a lot of gradient definitions that we need to port over to Zygote. Copying them over would be an easy patch for anyone interested in contributing.

**Comment by DoktorMike** [comment]
Good idea. Could you showcase just one such definition port? Might make it easier for someone to jump in. :)

**Comment by MikeInnes** [comment]
For example, [matmul in Tracker](https://github.com/FluxML/Tracker.jl/blob/ceba6f48fe79250feb0ecdeb999f4359186eaa3e/src/lib/array.jl#L375) and [matmul in Zygote](https://github.com/FluxML/Zygote.jl/blob/086859a4162a59fc7dcaad384f715a610a7ef641/src/lib/array.jl#L115).

In general the process is: copy it over to roughly the same place in `array.jl`, change `@grad` -> `@adjoint`, and remove any calls to `data`. Let me know if there's any other questions!

**Comment by c0nn3r** [comment]
I'm going to give this a try, thanks for the example!

**Comment by c0nn3r** [comment]
Sorry, just getting to this now. I've ported over the following functions (the copypaste job is done ;) )

- `view`
- `cat` (might need to be changed match how `vcat` and `hcat` are now implemented)
- `mean`
- `diagm`
- `dot`
- `det`
-  `logdet`
- `logabsdet`
- `inv`

Should I also port over the ones from NNLib.jl as well?

**Comment by MikeInnes** [comment]
There aren't any custom adjoints in NNlib, but there are some in Flux for NNlib – maybe that's what you mean. But yeah, it'd be good to have them.

**Comment by staticfloat** [comment]
Just a note that my branch `sf/nnlib_overhaul` addresses most of the NNlib adjoints, I think.

**Comment by ToucheSir** [comment]
Is this issue still relevant? The only remaining `@adjoints` I see would be [xlogy](https://github.com/FluxML/Flux.jl/blob/v0.12.4/src/losses/utils.jl#L21) (which should probably belong in NNlib if it can be rewritten as an `rrule`), and the normalization functions mentioned in https://github.com/FluxML/NNlib.jl/issues/19.

**Comment by DhairyaLGandhi** [comment]
Yeah we have basically done this one.
