### ISSUE TITLE
change repo description from "Intimate Affection Auditor"

### ISSUE THREAD

**Issue by stevengj** [FluxML/Zygote.jl#816]
While this was probably a cute joke at some point, at this point it should really be replaced by a useful description…

**Comment by dpmerrell** [comment]
![Screenshot from 2021-12-06 11-58-00](https://user-images.githubusercontent.com/14325161/144897490-8cbe85b6-519e-4eef-a30e-ce7d4b6c7bf8.png)

This is what shows up when I Google "julia zygote". I'm just getting into Julia's autodiff ecosystem, and was kind of confused at first glance.

**Comment by ToucheSir** [comment]
The previous tagline of "21st century AD" was arguably more informative while still maintaining some tongue-in-cheek levity. Happy to take suggestions for a new one (it need not be humorous, just reasonably terse).

**Comment by ToucheSir** [comment]
At some point between early December and now the description was reverted (couldn't figure out when), so closing this out.
