### ISSUE TITLE
Segfault on gradient of norm

### ISSUE THREAD

**Issue by jessebett** [FluxML/Zygote.jl#82]
```
using Flux
using Zygote
using LinearAlgebra:norm

F = Chain(Dense(1,10,σ),Dense(10,10))
Ft = mapleaves(Flux.data,F)

Flux.gradient(t->norm(Ft(t)),[1.]) #works in flux
Zygote.gradient(t->norm(Ft(t),[1.]) #seg fault
```

**Comment by willtebbutt** [comment]
Could just define a custom sensitivity (should probably be doing that anyway) to patch this, but it would be good to understand why this is happening.

@jessebett could you please report what `Zygote.usetyped` is set to?

**Comment by MikeInnes** [comment]
Can reproduce with `gradient(norm, [1, 2, 3])` (untyped mode and Julia master). Definitely worth debugging.

In case anyone is interested in debugging this, the trick is to call `_forward` and `back` directly, and look inside the definition of `norm` to try functions that it calls. Then you can find the call that actually calls this bug. (Should really write up some devdocs with examples like this.)

**Comment by willtebbutt** [comment]
Big fan of the dev docs idea :)

**Comment by jessebett** [comment]
@willtebbutt `Zygote.usetyped == false` 

And it's an uninformative segfault :p

**Comment by jessebett** [comment]
@MikeInnes  I agree that dev docs would be great. I tried `Zygote._forward(norm,[1.,2.])` and got `(2.23606797749979, J#typeof(norm)(...))` but I don't know what to do with this `Zygote.Pullback` object at all.

**Comment by MikeInnes** [comment]
In `y, back = _forward(f, x...)`, `back` is just the usual vjp, so you can call it on something with a similar shape to `y` (`dy`) and it'll give you `dx`s.

**Comment by jessebett** [comment]
Right, what I mean is that I don't know what I'm supposed to be doing with `back` to find the function it calls that is the bug. Calling `back` gives the segfault with no stack trace.

Or did you mean I should look at the definition of `norm` to see what might cause the bug?

**Comment by MikeInnes** [comment]
Right. Zygote calls `foo` and `bar`; you try `_forward(foo, x)` (with some made-up `x`) and `_forward(bar, x)`, along with their vjps, and see which one of them is causing the segfault. And then you can recurse until you see some function that has crazy control flow or uses some other language feature that we're not handling properly.

**Comment by MikeInnes** [comment]
Wrote up some [dev docs](http://fluxml.ai/Zygote.jl/dev/internals/). Let me know what else would be useful to know.

**Comment by MikeInnes** [comment]
Fixed in https://github.com/FluxML/Zygote.jl/commit/c49455bd581cf5660654e103590848df64754f3d. Segfault is still not differentiable but we now get a sensible error suggesting how to fix that.
