### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by devmotion** [FluxML/Zygote.jl#830]
I was surprised that the latest release of Zygote is still not compatible with FillArrays 0.10 (causing test failures in https://github.com/TuringLang/DistributionsAD.jl/pull/129) even though https://github.com/FluxML/Zygote.jl/pull/813 was merged a while ago.

Actually, if I'm not mistaken the latest release of Zygote is 0.5.9 (see https://github.com/FluxML/Zygote.jl/releases and https://github.com/JuliaRegistries/General/blob/master/Z/Zygote/Versions.toml). Since version 0.5.9, the version number in Project.toml has been updated multiple times (currently 0.5.12) but no new release has been made. Is it possible to fix this?

**Comment by willtebbutt** [comment]
Looks like I forgot to register 0.5.10 when we bumped `FillArrays`.

**Comment by willtebbutt** [comment]
Okay, we're nearly up to date. Once #831 has been merged and tagged, I'll close this issue.

**Comment by devmotion** [comment]
Thanks a lot!

**Comment by willtebbutt** [comment]
0.5.13 is [scheduled for release](https://github.com/JuliaRegistries/General/pull/24959), so I'm going to close this :)
