### ISSUE TITLE
Keeping function output

### ISSUE THREAD

**Issue by LeonardJohard** [FluxML/Zygote.jl#843]
Suppose I would like to calculate both the function output f(x) and gradient f'(x). Is there are way to do this efficiently? Otherwise it seems computing f'(x) and f(x) independently requires roughly 50 % more calculations than needed.

**Comment by CarloLucibello** [comment]
sure, you can use `pullback`
```julia
julia> f(x) = x^2
f (generic function with 1 method)

julia> y, pull = pullback(f, 3)
(9, Zygote.var"#41#42"{typeof(∂(f))}(∂(f)))

julia> pull(1) # equivalent to gradient(f, 3)
(6,)
```
