### ISSUE TITLE
Forward pass of getfield acts like getproperty in _pullback

### ISSUE THREAD

**Issue by mzgubic** [FluxML/Zygote.jl#851]
MWE
```
julia> using Zygote

julia> struct Funky
    x
    y
end

julia> f = Funky(1, 1);

julia> function Base.getproperty(f::Funky, i::Symbol)
    return 2
end

julia> getproperty(f, :x)
2

julia> getfield(f, :x)
1

julia> y, pb = Zygote._pullback(getproperty, f, :x) # y = 2, that's ok
(2, Zygote.var"#1704#back#159"{Zygote.var"#back#158"{:x,Zygote.Context,Funky,Int64}}(Zygote.var"#back#158"{:x,Zygote.Context,Funky,Int64}(Zygote.Context(nothing), Funky(1, 1), 2)))

julia> y, pb = Zygote._pullback(getfield, f, :x) # y = 2 but should be 1
(2, Zygote.var"#1704#back#159"{Zygote.var"#back#158"{:x,Zygote.Context,Funky,Int64}}(Zygote.var"#back#158"{:x,Zygote.Context,Funky,Int64}(Zygote.Context(nothing), Funky(1, 1), 2)))

```

I suspect [these lines](https://github.com/FluxML/Zygote.jl/blob/master/src/lib/lib.jl#L230-L231) are the issue.

Because then the pullback for `getfield` [will just call `getproperty`](https://github.com/FluxML/Zygote.jl/blob/master/src/lib/lib.jl#L213).

Could we just define a similar `_pullback` for `getfield`?

**Comment by simeonschaub** [comment]
This should be fixed by #848, since this was breaking stuff for NamedTuples in 1.6. I was actually a bit surprised that no one ran into problems with that before, but didn't really question this further. In retrospect, I should probably have opened a dedicated issue.
