### ISSUE TITLE
accum NamedTuple sometimes silently drops derivatives

### ISSUE THREAD

**Issue by willtebbutt** [FluxML/Zygote.jl#861]
This works correctly:
```julia
julia> Zygote.accum((a=nothing, b=4), (a=4,))
(a = 4, b = 4)
```

This drops the derivative w.r.t. `b`:
```julia
julia> Zygote.accum((a=4, ), (a=nothing, b=4))
(a = 4,)
```
Now this is definitely surprising, and I _think_ it's a bug. The only situation in which it's intended behaviour is if it's the case that the derivative w.r.t. some struct should always be a `NamedTuple` containing _all_ of the associated fields, since this would preclude this kind of problem.

Note that ChainRule types don't suffer from this issue:
```julia
julia> Composite{Any}(; a=4) + Composite{Any}(; a=Zero(), b=4)
Composite{Any}(a = 4, b = 4)
```
so we can probably nick the `ChainRulesCore` implementation of `+` for `Composite`s and deploy it for `accum` with `NamedTuple`s.

**Comment by willtebbutt** [comment]
Although looking at what `Zygote` does by default, perhaps it _is_ assumed that all fields will always be present and I just missed the memo on that one?
```julia
julia> Zygote.gradient(x -> sin(x.a), (a=4,b=4))
((a = -0.6536436208636119, b = nothing),)
```
(Had the gradient not had a field `b`, it would clearly be the case that `Zygote` doesn't make this assumption).

**Comment by oxinabox** [comment]
>  The only situation in which it's intended behaviour is if it's the case that the derivative w.r.t. some struct should always be a NamedTuple containing all of the associated fields, since this would preclude this kind of problem.

This is the case. As I understand it.
Zygote requires all structural derivatives to be NamedTuples with the same fields (in the same order?)  as the primal type.
What ChainRules calls the _canonical_ form.

As such `Zygote.accum((a=nothing, b=4), (a=4,))`
and `Zygote.accum((a=4, ), (a=nothing, b=4))`
should both error.
Since it means something went wrong somewhere to give you a bad dertivative.
Probably an incorrect rule.

**Comment by willtebbutt** [comment]
> Since it means something went wrong somewhere to give you a bad dertivative.
> Probably an incorrect rule.

This is exactly what happened. I returned a subset of the required fields from a particular hand-writen `_pullback`.

**Comment by mzgubic** [comment]
Closed by https://github.com/FluxML/Zygote.jl/pull/924
