### ISSUE TITLE
Compat

### ISSUE THREAD

**Issue by mloubout** [FluxML/Zygote.jl#867]
The latest version `v0.6` is not compatible with the latest Flux (and CUDA) versions because of different restricted `Adapt` versions. Is this on the roadmap?

**Comment by DhairyaLGandhi** [comment]
Yup

**Comment by mloubout** [comment]
In the mean time, is there a way to force Zygote (0.5.17) to ignore the `@adjoint NNlib.conv` and to use rrule instead? It seems to default to @adjoint when it exists.

**Comment by DhairyaLGandhi** [comment]
Delete the adjoint locally?

**Comment by mloubout** [comment]
How would I do that?

**Comment by CarloLucibello** [comment]
Something you can do is wrap `conv` with a dummy function
```julia
myconv(x...; kws...) = conv(x...; kws...)
```
then define a `rrule` for `myconv`

**Comment by CarloLucibello** [comment]
Before tagging a Flux release compatible with Zygote 0.6 we have to merge these  PRs
https://github.com/FluxML/Flux.jl/pulls?q=is%3Aopen+is%3Apr+milestone%3Av0.12
Any review comment and Approvals can speedup the process

**Comment by mloubout** [comment]
>myconv(x...; kws...) = conv(x...; kws...)

Well that's not really doable since `conv` is called in Flux, and I don't want to have Flux and all its dependencies just for that. Found another workaround for now hopefully will work in the future.

Closing.
