### ISSUE TITLE
Document "adjoint" more clearly

### ISSUE THREAD

**Issue by leventov** [FluxML/Zygote.jl#869]
The section "Custom Adjoints" (or, in fact, the "Home" section, or the README on Github) doesn't clearly describe what an "adjoint" is in Zygote's (or mathematical) terms, and what `@adjoint` _should_ do. All the documentation pieces that I found assumes that the reader already understands that.

Also, it seems that the terms "adjoint" and "gradient" are sometimes used as synonyms, but I'm 100% sure. I think it would be useful to make this explicit, too.

**Comment by gxyd** [comment]
Definitely agree with you, when I first read the documentation a few of the things were unclear to me. Fortunately I came across [this comment on reddit](https://www.reddit.com/r/MachineLearning/comments/6gvv0o/r_first_blog_post_a_new_trick_for_calculating/ditrcqn), which said:

> This works because what is mostly called "gradient" in machine learning is "actually" the adjoint of the derivative operator. I personally always found this much more clear than calling it gradients.

This clarified quite a bit for me.

**Comment by CarloLucibello** [comment]
closing this, as `@adjoint` will be deprecated in favor of `ChainRules.rrule`
